function projectRoot = setup_amr_project()
%SETUP_AMR_PROJECT Add AMR folders to the MATLAB path without a project.
%   Prefer opening AMRRobotPlanning.prj for normal work. This function is a
%   lightweight fallback for temporary MATLAB sessions.

projectRoot = fileparts(mfilename("fullpath"));
addpath( ...
    fullfile(projectRoot, "scripts"), ...
    fullfile(projectRoot, "src"), ...
    fullfile(projectRoot, "tests", "unit"), ...
    fullfile(projectRoot, "models", "mission_supervisor"), ...
    fullfile(projectRoot, "models", "mission_supervisor", "versions"), ...
    fullfile(projectRoot, "models", "mission_supervisor", "comparison"), ...
    fullfile(projectRoot, "models", "integrated_system"), ...
    fullfile(projectRoot, "models", "examples"));

fprintf("AMR project ready: %s\n", projectRoot);
end
