function report = assertCollisionFreePlayback(playbackData, floorMap)
%ASSERTCOLLISIONFREEPLAYBACK Fail if any robot translation crosses occupancy.

includeDynamicObstacle = playbackData.scenarioId == 2;
safetyGrid = amr.mapping.rasterizeFloorMap( ...
    floorMap, 10, 0.30, includeDynamicObstacle);
sampleCount = numel(playbackData.time);

for index = 1:sampleCount
    position = [playbackData.x(index), playbackData.y(index)];
    assert(~amr.mapping.isWorldPointOccupied(safetyGrid, position), ...
        "AMR:PoseInCollision", ...
        "Scenario %s occupies an inflated obstacle at t=%.2f s, pose=[%.3f %.3f].", ...
        playbackData.scenarioName, playbackData.time(index), position);
    if index > 1
        previousPosition = [playbackData.x(index - 1), playbackData.y(index - 1)];
        assert(amr.mapping.isSegmentCollisionFree( ...
            safetyGrid, previousPosition, position), ...
            "AMR:SegmentInCollision", ...
            "Scenario %s crosses an inflated obstacle from t=%.2f to %.2f s.", ...
            playbackData.scenarioName, playbackData.time(index - 1), ...
            playbackData.time(index));
    end
end

report = struct( ...
    "passed", true, ...
    "sampleCount", sampleCount, ...
    "inflationRadius", safetyGrid.inflationRadius, ...
    "dynamicObstacleIncluded", includeDynamicObstacle);
end
