function window = computeDynamicWindow(currentCommand, config)
%COMPUTEDYNAMICWINDOW Intersect physical limits with one-step acceleration limits.

arguments
    currentCommand (1, 2) double
    config struct = amr.planning.createDwaConfig()
end

timeStep = config.controlSampleTime;
window = [ ...
    max(config.minimumLinearVelocity, currentCommand(1) - ...
        config.maximumLinearAcceleration * timeStep), ...
    min(config.maximumLinearVelocity, currentCommand(1) + ...
        config.maximumLinearAcceleration * timeStep), ...
    max(-config.maximumAngularVelocity, currentCommand(2) - ...
        config.maximumAngularAcceleration * timeStep), ...
    min(config.maximumAngularVelocity, currentCommand(2) + ...
        config.maximumAngularAcceleration * timeStep)];
end
