function localMap = extractLocalCostmap(globalMap, center, windowSize)
%EXTRACTLOCALCOSTMAP Extract an axis-aligned robot-centred grid window.

arguments
    globalMap struct
    center (1, 2) double
    windowSize (1, 2) double {mustBePositive} = [6, 6]
end

xLimits = center(1) + 0.5 * windowSize(1) * [-1, 1];
yLimits = center(2) + 0.5 * windowSize(2) * [-1, 1];
columnMask = globalMap.xCenters >= xLimits(1) & ...
    globalMap.xCenters <= xLimits(2);
rowMask = globalMap.yCenters >= yLimits(1) & ...
    globalMap.yCenters <= yLimits(2);
assert(any(columnMask) && any(rowMask), "AMR:LocalCostmapOutside", ...
    "Local costmap does not overlap the global map.");

columns = find(columnMask);
rows = find(rowMask);
cellHalfWidth = 0.5 / globalMap.resolution;
xCenters = globalMap.xCenters(columns);
yCenters = globalMap.yCenters(rows);
localMap = struct( ...
    "occupancy", globalMap.occupancy(rows, columns), ...
    "resolution", globalMap.resolution, ...
    "inflationRadius", globalMap.inflationRadius, ...
    "bounds", [xCenters(1) - cellHalfWidth, ...
        xCenters(end) + cellHalfWidth, yCenters(1) - cellHalfWidth, ...
        yCenters(end) + cellHalfWidth], ...
    "xCenters", xCenters, ...
    "yCenters", yCenters);
end
