function detection = evaluateLidarSafety(scan, config)
%EVALUATELIDARSAFETY Evaluate rectangular stop and slowdown zones.

arguments
    scan struct
    config struct = amr.sensors.createLidarConfig()
end

forwardDistance = config.mountingOffset(1) + ...
    scan.ranges .* cos(scan.angleOffsets);
lateralDistance = config.mountingOffset(2) + ...
    scan.ranges .* sin(scan.angleOffsets);
validForwardHit = scan.hitMask & forwardDistance > 0;
slowdownMask = validForwardHit & ...
    forwardDistance <= config.slowdownDistance & ...
    abs(lateralDistance) <= config.slowdownHalfWidth;
stopMask = validForwardHit & ...
    forwardDistance <= config.stopDistance & ...
    abs(lateralDistance) <= config.stopHalfWidth;

frontCandidates = validForwardHit & ...
    abs(lateralDistance) <= config.slowdownHalfWidth;
if any(frontCandidates)
    frontRange = min(forwardDistance(frontCandidates));
else
    frontRange = config.maximumRange;
end

detection = struct( ...
    "slowdownActive", any(slowdownMask), ...
    "protectiveStopActive", any(stopMask), ...
    "frontRange", frontRange, ...
    "slowdownBeamMask", slowdownMask, ...
    "stopBeamMask", stopMask);
end
