function config = createSupervisorConfig(options)
%CREATESUPERVISORCONFIG Create deterministic AMR supervisor parameters.
%   All durations are in seconds. State-of-charge thresholds are fractions
%   in the closed interval [0, 1]. The returned structure has no base
%   workspace dependencies and is suitable for use as a model parameter.

arguments
    options.SupervisorSampleTime (1,1) ...
        {mustBeFloat, mustBeReal, mustBeFinite, mustBePositive} = 0.10
    options.BootTimeout (1,1) ...
        {mustBeFloat, mustBeReal, mustBeFinite, mustBePositive} = 5.0
    options.JobValidationTimeout (1,1) ...
        {mustBeFloat, mustBeReal, mustBeFinite, mustBePositive} = 1.0
    options.PlannerResponseTimeout (1,1) ...
        {mustBeFloat, mustBeReal, mustBeFinite, mustBePositive} = 2.0
    options.PayloadHandshakeTimeout (1,1) ...
        {mustBeFloat, mustBeReal, mustBeFinite, mustBePositive} = 10.0
    options.CommunicationFreshnessTimeout (1,1) ...
        {mustBeFloat, mustBeReal, mustBeFinite, mustBePositive} = 0.30
    options.MaximumRecoveryRetries (1,1) ...
        {mustBeNumeric, mustBeReal, mustBeFinite, mustBeInteger, ...
        mustBeNonnegative} = 3
    options.MinimumRecoveryActionHoldTime (1,1) ...
        {mustBeFloat, mustBeReal, mustBeFinite, mustBePositive} = 0.50
    options.RecoveryTotalTimeout (1,1) ...
        {mustBeFloat, mustBeReal, mustBeFinite, mustBePositive} = 12.0
    options.CriticalSoc (1,1) ...
        {mustBeFloat, mustBeReal, mustBeFinite, mustBeNonnegative, ...
        mustBeLessThanOrEqual(options.CriticalSoc, 1)} = 0.12
    options.LowSoc (1,1) ...
        {mustBeFloat, mustBeReal, mustBeFinite, mustBeNonnegative, ...
        mustBeLessThanOrEqual(options.LowSoc, 1)} = 0.25
    options.ResumeSoc (1,1) ...
        {mustBeFloat, mustBeReal, mustBeFinite, mustBeNonnegative, ...
        mustBeLessThanOrEqual(options.ResumeSoc, 1)} = 0.80
    options.MinimumDwellTime (1,1) ...
        {mustBeFloat, mustBeReal, mustBeFinite, mustBePositive} = 0.20
    options.StopResponseLimit (1,1) ...
        {mustBeFloat, mustBeReal, mustBeFinite, mustBeNonnegative} = 0.10
end

sampleTime = double(options.SupervisorSampleTime);
timeoutValues = double([ ...
    options.BootTimeout, ...
    options.JobValidationTimeout, ...
    options.PlannerResponseTimeout, ...
    options.PayloadHandshakeTimeout, ...
    options.CommunicationFreshnessTimeout, ...
    options.MinimumRecoveryActionHoldTime, ...
    options.RecoveryTotalTimeout]);

if any(timeoutValues < sampleTime)
    error("AMR:Supervision:InvalidTimeout", ...
        "Every timeout and hold time must be at least one supervisor sample.");
end

if options.MinimumDwellTime < options.SupervisorSampleTime
    error("AMR:Supervision:InvalidMinimumDwellTime", ...
        "MinimumDwellTime must be at least one supervisor sample.");
end

if options.MaximumRecoveryRetries > double(intmax("uint8"))
    error("AMR:Supervision:InvalidRecoveryRetryCount", ...
        "MaximumRecoveryRetries must fit in uint8.");
end

if ~(options.CriticalSoc < options.LowSoc && ...
        options.LowSoc < options.ResumeSoc)
    error("AMR:Supervision:InvalidEnergyThresholds", ...
        "Energy thresholds must satisfy CriticalSoc < LowSoc < ResumeSoc.");
end

config.schemaVersion = uint16(1);
config.supervisorSampleTime = sampleTime;

config.timeouts.bootSeconds = double(options.BootTimeout);
config.timeouts.jobValidationSeconds = ...
    double(options.JobValidationTimeout);
config.timeouts.plannerResponseSeconds = ...
    double(options.PlannerResponseTimeout);
config.timeouts.payloadHandshakeSeconds = ...
    double(options.PayloadHandshakeTimeout);
config.timeouts.communicationFreshnessSeconds = ...
    double(options.CommunicationFreshnessTimeout);

config.recovery.maximumRetries = uint8(options.MaximumRecoveryRetries);
config.recovery.minimumActionHoldSeconds = ...
    double(options.MinimumRecoveryActionHoldTime);
config.recovery.totalTimeoutSeconds = ...
    double(options.RecoveryTotalTimeout);

config.energy.criticalSoc = double(options.CriticalSoc);
config.energy.lowSoc = double(options.LowSoc);
config.energy.resumeSoc = double(options.ResumeSoc);

config.telemetry.minimumDwellSeconds = double(options.MinimumDwellTime);
config.telemetry.stopResponseLimitSeconds = ...
    double(options.StopResponseLimit);
config.telemetry.timeComparisonToleranceSeconds = 1.0e-9;

config.defaults.lifecycleMode = ...
    amr.supervision.LifecycleMode.getDefaultValue();
config.defaults.missionMode = ...
    amr.supervision.MissionMode.getDefaultValue();
config.defaults.navigationMode = ...
    amr.supervision.NavigationMode.getDefaultValue();
config.defaults.safetyMode = ...
    amr.supervision.SafetyMode.getDefaultValue();
config.defaults.energyMode = ...
    amr.supervision.EnergyMode.getDefaultValue();
config.defaults.healthMode = ...
    amr.supervision.HealthMode.getDefaultValue();
config.defaults.faultReason = ...
    amr.supervision.FaultReason.getDefaultValue();
config.defaults.recoveryAction = ...
    amr.supervision.RecoveryAction.getDefaultValue();
end
