function metrics = evaluateSupervisorTelemetry(telemetry, config)
%EVALUATESUPERVISORTELEMETRY Evaluate sampled AMR supervisor behavior.
%   METRICS = EVALUATESUPERVISORTELEMETRY(TELEMETRY) evaluates state
%   transitions, zero-order-hold dwell time, A-B-A chattering episodes,
%   recovery/fault events, and motion-inhibit response.
%
%   TELEMETRY is a scalar structure with equally sized vector fields:
%     timeSeconds, lifecycleMode, missionMode, navigationMode, safetyMode,
%     energyMode, healthMode, faultReason, recoveryAction, motionPermit.
%   Mode fields may contain the corresponding amr.supervision enum or
%   integer-valued numeric codes. motionPermit must be logical.

arguments
    telemetry (1,1) {mustBeA(telemetry, "struct")}
    config (1,1) {mustBeA(config, "struct")} = ...
        amr.supervision.createSupervisorConfig()
end

validateConfig(config);
validateRequiredFields(telemetry);

timeSeconds = normalizeTime(telemetry.timeSeconds);
sampleCount = numel(timeSeconds);

lifecycleMode = normalizeMode(telemetry.lifecycleMode, ...
    "lifecycleMode", sampleCount, ...
    "amr.supervision.LifecycleMode", int32(0:5));
missionMode = normalizeMode(telemetry.missionMode, ...
    "missionMode", sampleCount, ...
    "amr.supervision.MissionMode", int32(0:9));
navigationMode = normalizeMode(telemetry.navigationMode, ...
    "navigationMode", sampleCount, ...
    "amr.supervision.NavigationMode", int32(0:5));
safetyMode = normalizeMode(telemetry.safetyMode, ...
    "safetyMode", sampleCount, ...
    "amr.supervision.SafetyMode", int32(0:2));
energyMode = normalizeMode(telemetry.energyMode, ...
    "energyMode", sampleCount, ...
    "amr.supervision.EnergyMode", int32(0:4));
healthMode = normalizeMode(telemetry.healthMode, ...
    "healthMode", sampleCount, ...
    "amr.supervision.HealthMode", int32(0:2));
faultReason = normalizeMode(telemetry.faultReason, ...
    "faultReason", sampleCount, ...
    "amr.supervision.FaultReason", int32(0:10));
recoveryAction = normalizeMode(telemetry.recoveryAction, ...
    "recoveryAction", sampleCount, ...
    "amr.supervision.RecoveryAction", int32(0:6));
motionPermit = normalizeMotionPermit(telemetry.motionPermit, sampleCount);

minimumDwell = config.telemetry.minimumDwellSeconds;
metrics.schemaVersion = uint16(1);
metrics.sampleCount = uint32(sampleCount);
metrics.durationSeconds = timeSeconds(end) - timeSeconds(1);
metrics.lifecycle = summarizeMode( ...
    timeSeconds, lifecycleMode, minimumDwell);
metrics.mission = summarizeMode( ...
    timeSeconds, missionMode, minimumDwell);
metrics.navigation = summarizeMode( ...
    timeSeconds, navigationMode, minimumDwell);
metrics.safetyMode = summarizeMode( ...
    timeSeconds, safetyMode, minimumDwell);
metrics.energy = summarizeMode( ...
    timeSeconds, energyMode, minimumDwell);
metrics.health = summarizeMode( ...
    timeSeconds, healthMode, minimumDwell);
metrics.faultReason = summarizeMode( ...
    timeSeconds, faultReason, minimumDwell);
metrics.recoveryAction = summarizeMode( ...
    timeSeconds, recoveryAction, minimumDwell);

faultLatchedCode = int32(amr.supervision.LifecycleMode.FaultLatched);
emergencyStopCode = ...
    int32(amr.supervision.LifecycleMode.EmergencyStopLatched);
protectiveStopCode = int32(amr.supervision.SafetyMode.ProtectiveStop);
stopRequired = safetyMode == protectiveStopCode | ...
    lifecycleMode == faultLatchedCode | ...
    lifecycleMode == emergencyStopCode;

metrics.stopResponse = summarizeStopResponse( ...
    timeSeconds, stopRequired, motionPermit, ...
    config.telemetry.stopResponseLimitSeconds, ...
    config.telemetry.timeComparisonToleranceSeconds);

metrics.events.missionCompletedCount = countEntries( ...
    missionMode == int32(amr.supervision.MissionMode.Completed));
metrics.events.faultLatchedCount = countEntries( ...
    lifecycleMode == faultLatchedCode);
metrics.events.emergencyStopCount = countEntries( ...
    lifecycleMode == emergencyStopCode);
metrics.events.plannerTimeoutCount = countEntries( ...
    faultReason == int32(amr.supervision.FaultReason.PlannerTimeout));
metrics.events.recoveryExhaustedCount = countEntries( ...
    faultReason == int32(amr.supervision.FaultReason.RecoveryExhausted));
metrics.events.recoveryActionRequestCount = ...
    countActionRequests(recoveryAction);

powerOffCode = int32(amr.supervision.LifecycleMode.PowerOff);
bootCode = int32(amr.supervision.LifecycleMode.Boot);
shutdownCode = ...
    int32(amr.supervision.LifecycleMode.ControlledShutdown);
motionForbidden = lifecycleMode == powerOffCode | ...
    lifecycleMode == bootCode | lifecycleMode == shutdownCode;
metrics.invariants.nonOperationalMotionPermitSamples = ...
    uint32(sum(motionForbidden & motionPermit));
metrics.invariants.lateStopMotionPermitSamples = ...
    metrics.stopResponse.lateMotionPermitSamples;

chatteringCounts = double([ ...
    metrics.lifecycle.chatteringCount, ...
    metrics.mission.chatteringCount, ...
    metrics.navigation.chatteringCount, ...
    metrics.safetyMode.chatteringCount, ...
    metrics.energy.chatteringCount, ...
    metrics.health.chatteringCount, ...
    metrics.faultReason.chatteringCount, ...
    metrics.recoveryAction.chatteringCount]);
metrics.totalChatteringCount = uint32(sum(chatteringCounts));

metrics.overallPass = ...
    metrics.stopResponse.missedDeadlineCount == 0 && ...
    metrics.invariants.nonOperationalMotionPermitSamples == 0 && ...
    metrics.invariants.lateStopMotionPermitSamples == 0 && ...
    metrics.totalChatteringCount == 0;
end

function validateRequiredFields(telemetry)
requiredFields = [ ...
    "timeSeconds", ...
    "lifecycleMode", ...
    "missionMode", ...
    "navigationMode", ...
    "safetyMode", ...
    "energyMode", ...
    "healthMode", ...
    "faultReason", ...
    "recoveryAction", ...
    "motionPermit"];

for fieldIndex = 1:numel(requiredFields)
    fieldName = requiredFields(fieldIndex);
    if ~isfield(telemetry, fieldName)
        error("AMR:Supervision:MissingTelemetryField", ...
            "Telemetry is missing required field '%s'.", fieldName);
    end
end
end

function validateConfig(config)
valid = isfield(config, "supervisorSampleTime") && ...
    isfield(config, "telemetry") && ...
    isstruct(config.telemetry) && ...
    isfield(config.telemetry, "minimumDwellSeconds") && ...
    isfield(config.telemetry, "stopResponseLimitSeconds") && ...
    isfield(config.telemetry, "timeComparisonToleranceSeconds");

if ~valid
    error("AMR:Supervision:InvalidConfig", ...
        "Config does not contain the required telemetry parameters.");
end

values = [ ...
    config.supervisorSampleTime, ...
    config.telemetry.minimumDwellSeconds, ...
    config.telemetry.stopResponseLimitSeconds, ...
    config.telemetry.timeComparisonToleranceSeconds];
if ~(isfloat(values) && isreal(values) && ...
        all(isfinite(values)) && all(values >= 0) && ...
        config.supervisorSampleTime > 0 && ...
        config.telemetry.minimumDwellSeconds > 0)
    error("AMR:Supervision:InvalidConfig", ...
        "Telemetry timing parameters must be finite, real scalars.");
end
end

function timeSeconds = normalizeTime(value)
if ~(isfloat(value) && isreal(value) && isvector(value) && ...
        ~isempty(value) && all(isfinite(value), "all"))
    error("AMR:Supervision:InvalidTime", ...
        "timeSeconds must be a nonempty finite real floating-point vector.");
end

timeSeconds = double(value(:));
if any(diff(timeSeconds) <= 0)
    error("AMR:Supervision:NonIncreasingTime", ...
        "timeSeconds must be strictly increasing.");
end
end

function codes = normalizeMode( ...
        value, fieldName, sampleCount, expectedClass, validCodes)
if ~(isvector(value) && numel(value) == sampleCount)
    error("AMR:Supervision:TelemetryLengthMismatch", ...
        "Telemetry field '%s' must match timeSeconds.", fieldName);
end

if isa(value, "Simulink.IntEnumType")
    if ~isa(value, expectedClass)
        error("AMR:Supervision:InvalidModeType", ...
            "Telemetry field '%s' uses the wrong enum class.", fieldName);
    end
    codes = int32(value(:));
elseif isnumeric(value) && isreal(value) && ...
        all(isfinite(value), "all") && ...
        all(value == fix(value), "all")
    numericValue = double(value(:));
    if any(numericValue < double(intmin("int32"))) || ...
            any(numericValue > double(intmax("int32")))
        error("AMR:Supervision:InvalidModeCode", ...
            "Telemetry field '%s' contains an out-of-range code.", fieldName);
    end
    codes = int32(numericValue);
else
    error("AMR:Supervision:InvalidModeType", ...
        "Telemetry field '%s' must contain an integer code or enum.", ...
        fieldName);
end

if any(~ismember(codes, validCodes))
    error("AMR:Supervision:InvalidModeCode", ...
        "Telemetry field '%s' contains an undefined mode code.", fieldName);
end
end

function motionPermit = normalizeMotionPermit(value, sampleCount)
if ~(islogical(value) && isvector(value) && ...
        numel(value) == sampleCount)
    error("AMR:Supervision:InvalidMotionPermit", ...
        "motionPermit must be a logical vector matching timeSeconds.");
end
motionPermit = value(:);
end

function summary = summarizeMode(timeSeconds, codes, minimumDwell)
sampleCount = numel(timeSeconds);
changeIndices = find(diff(codes) ~= 0) + 1;
episodeStartIndices = [1; changeIndices];
episodeEndIndices = [changeIndices - 1; sampleCount];
episodeCount = numel(episodeStartIndices);
episodeCodes = codes(episodeStartIndices);
episodeDwellSeconds = zeros(episodeCount, 1);

for episodeIndex = 1:episodeCount
    if episodeEndIndices(episodeIndex) < sampleCount
        boundaryIndex = episodeEndIndices(episodeIndex) + 1;
    else
        boundaryIndex = sampleCount;
    end
    episodeDwellSeconds(episodeIndex) = ...
        timeSeconds(boundaryIndex) - ...
        timeSeconds(episodeStartIndices(episodeIndex));
end

stateCodes = unique(codes, "stable");
stateCount = numel(stateCodes);
stateDwellSeconds = zeros(stateCount, 1);
stateVisitCount = zeros(stateCount, 1, "uint32");
intervalSeconds = diff(timeSeconds);
intervalCodes = codes(1:end-1);

for stateIndex = 1:stateCount
    stateCode = stateCodes(stateIndex);
    stateDwellSeconds(stateIndex) = ...
        sum(intervalSeconds(intervalCodes == stateCode));
    stateVisitCount(stateIndex) = ...
        uint32(sum(episodeCodes == stateCode));
end

chatteringCount = uint32(0);
for episodeIndex = 2:(episodeCount - 1)
    returnedToPreviousState = ...
        episodeCodes(episodeIndex - 1) == ...
        episodeCodes(episodeIndex + 1);
    shortEpisode = episodeDwellSeconds(episodeIndex) < minimumDwell;
    if returnedToPreviousState && shortEpisode
        chatteringCount = chatteringCount + 1;
    end
end

summary.transitionCount = uint32(numel(changeIndices));
summary.episodeCount = uint32(episodeCount);
summary.chatteringCount = chatteringCount;
summary.stateCodes = stateCodes;
summary.stateDwellSeconds = stateDwellSeconds;
summary.stateVisitCount = stateVisitCount;
summary.transitionTimesSeconds = timeSeconds(changeIndices);
summary.episodeCodes = episodeCodes;
summary.episodeStartTimesSeconds = ...
    timeSeconds(episodeStartIndices);
summary.episodeDwellSeconds = episodeDwellSeconds;
end

function summary = summarizeStopResponse( ...
        timeSeconds, stopRequired, motionPermit, responseLimit, tolerance)
sampleCount = numel(timeSeconds);
stopEntryIndices = find(stopRequired & ...
    [true; ~stopRequired(1:end-1)]);
requestCount = numel(stopEntryIndices);
responseTimesSeconds = zeros(requestCount, 1);
lateMotionPermitSamples = uint32(0);

for requestIndex = 1:requestCount
    startIndex = stopEntryIndices(requestIndex);
    exitOffset = find(~stopRequired(startIndex:end), 1, "first");
    if isempty(exitOffset)
        endIndex = sampleCount;
    else
        endIndex = startIndex + exitOffset - 2;
    end

    inhibitOffset = find( ...
        ~motionPermit(startIndex:endIndex), 1, "first");
    if isempty(inhibitOffset)
        responseTimesSeconds(requestIndex) = Inf;
    else
        inhibitIndex = startIndex + inhibitOffset - 1;
        responseTimesSeconds(requestIndex) = ...
            timeSeconds(inhibitIndex) - timeSeconds(startIndex);
    end

    episodeTimes = timeSeconds(startIndex:endIndex);
    episodeMotionPermit = motionPermit(startIndex:endIndex);
    deadlineExceeded = ...
        (episodeTimes - timeSeconds(startIndex)) > ...
        (responseLimit + tolerance);
    lateMotionPermitSamples = lateMotionPermitSamples + ...
        uint32(sum(episodeMotionPermit & deadlineExceeded));
end

if isempty(responseTimesSeconds)
    maximumResponseTimeSeconds = 0.0;
else
    maximumResponseTimeSeconds = max(responseTimesSeconds);
end

summary.requestCount = uint32(requestCount);
summary.responseTimesSeconds = responseTimesSeconds;
summary.maximumResponseTimeSeconds = maximumResponseTimeSeconds;
summary.missedDeadlineCount = uint32(sum( ...
    responseTimesSeconds > (responseLimit + tolerance)));
summary.motionPermitWhileStopRequestedSamples = ...
    uint32(sum(stopRequired & motionPermit));
summary.lateMotionPermitSamples = lateMotionPermitSamples;
end

function count = countEntries(mask)
count = uint32(mask(1)) + ...
    uint32(sum(~mask(1:end-1) & mask(2:end)));
end

function count = countActionRequests(recoveryAction)
noneCode = int32(amr.supervision.RecoveryAction.None);
initialRequest = recoveryAction(1) ~= noneCode;
changedToAction = ...
    recoveryAction(2:end) ~= recoveryAction(1:end-1) & ...
    recoveryAction(2:end) ~= noneCode;
count = uint32(initialRequest) + uint32(sum(changedToAction));
end
