function modelPath = build_amr_milestone01_skeleton()
%BUILD_AMR_MILESTONE01_SKELETON Create the Simulink plant and empty chart.
%   Stateflow states and chart data are added separately through model_edit.

projectRoot = fileparts(fileparts(mfilename('fullpath')));
modelDirectory = fullfile(projectRoot, 'models', 'prototypes');
modelName = 'amr_milestone01';
modelPath = fullfile(modelDirectory, modelName + ".slx");

if isfile(modelPath)
    error('AMR:ModelAlreadyExists', ...
        'Model already exists and will not be overwritten: %s', modelPath);
end

params = create_default_amr_params();
new_system(modelName);
cleanup = onCleanup(@() closeModelIfLoaded(modelName));

add_block('sflib/Chart', modelName + "/MissionSupervisor", ...
    'Position', [60, 80, 250, 210]);
add_block('simulink/Ports & Subsystems/Subsystem', ...
    modelName + "/DifferentialDrivePlant", ...
    'Position', [350, 65, 570, 245]);
buildPlantSubsystem(modelName + "/DifferentialDrivePlant", params);

add_block('simulink/Sinks/To Workspace', modelName + "/LogStateId", ...
    'VariableName', 'stateIdLog', 'SaveFormat', 'Timeseries', ...
    'Position', [660, 25, 785, 55]);
add_block('simulink/Sinks/To Workspace', modelName + "/LogVCmd", ...
    'VariableName', 'vCmdLog', 'SaveFormat', 'Timeseries', ...
    'Position', [660, 70, 785, 100]);
add_block('simulink/Sinks/To Workspace', modelName + "/LogWCmd", ...
    'VariableName', 'wCmdLog', 'SaveFormat', 'Timeseries', ...
    'Position', [660, 115, 785, 145]);
add_block('simulink/Sinks/To Workspace', modelName + "/LogX", ...
    'VariableName', 'xLog', 'SaveFormat', 'Timeseries', ...
    'Position', [660, 170, 785, 200]);
add_block('simulink/Sinks/To Workspace', modelName + "/LogY", ...
    'VariableName', 'yLog', 'SaveFormat', 'Timeseries', ...
    'Position', [660, 215, 785, 245]);
add_block('simulink/Sinks/To Workspace', modelName + "/LogTheta", ...
    'VariableName', 'thetaLog', 'SaveFormat', 'Timeseries', ...
    'Position', [660, 260, 785, 290]);
add_block('simulink/Sinks/To Workspace', modelName + "/LogWheelLeft", ...
    'VariableName', 'wheelLeftLog', 'SaveFormat', 'Timeseries', ...
    'Position', [660, 305, 785, 335]);
add_block('simulink/Sinks/To Workspace', modelName + "/LogWheelRight", ...
    'VariableName', 'wheelRightLog', 'SaveFormat', 'Timeseries', ...
    'Position', [660, 350, 785, 380]);

set_param(modelName, ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', num2str(params.sampleTime.plant, '%.15g'), ...
    'StopTime', num2str(params.simulation.stopTime, '%.15g'), ...
    'ReturnWorkspaceOutputs', 'on');

save_system(modelName, modelPath);
clear cleanup;
close_system(modelName, 0);
fprintf('Created model skeleton: %s\n', modelPath);
end

function buildPlantSubsystem(subsystemPath, params)
Simulink.SubSystem.deleteContents(subsystemPath);

add_block('simulink/Sources/In1', subsystemPath + "/vCmd", ...
    'Port', '1', 'Position', [25, 45, 55, 65]);
add_block('simulink/Sources/In1', subsystemPath + "/wCmd", ...
    'Port', '2', 'Position', [25, 135, 55, 155]);

add_block('simulink/Math Operations/Gain', subsystemPath + "/LeftFromV", ...
    'Gain', num2str(1 / params.robot.wheelRadius, '%.15g'), ...
    'Position', [90, 25, 145, 55]);
add_block('simulink/Math Operations/Gain', subsystemPath + "/LeftFromW", ...
    'Gain', num2str(-params.robot.trackWidth / (2 * params.robot.wheelRadius), '%.15g'), ...
    'Position', [90, 85, 145, 115]);
add_block('simulink/Math Operations/Sum', subsystemPath + "/WheelLeft", ...
    'Inputs', '++', 'Position', [190, 45, 215, 75]);

add_block('simulink/Math Operations/Gain', subsystemPath + "/RightFromV", ...
    'Gain', num2str(1 / params.robot.wheelRadius, '%.15g'), ...
    'Position', [90, 205, 145, 235]);
add_block('simulink/Math Operations/Gain', subsystemPath + "/RightFromW", ...
    'Gain', num2str(params.robot.trackWidth / (2 * params.robot.wheelRadius), '%.15g'), ...
    'Position', [90, 265, 145, 295]);
add_block('simulink/Math Operations/Sum', subsystemPath + "/WheelRight", ...
    'Inputs', '++', 'Position', [190, 225, 215, 255]);

add_block('simulink/Discrete/Discrete-Time Integrator', ...
    subsystemPath + "/ThetaIntegrator", ...
    'gainval', '1', 'InitialCondition', '0', ...
    'SampleTime', num2str(params.sampleTime.plant, '%.15g'), ...
    'Position', [285, 130, 340, 165]);
add_block('simulink/Math Operations/Trigonometric Function', ...
    subsystemPath + "/CosTheta", 'Operator', 'cos', ...
    'Position', [390, 85, 440, 115]);
add_block('simulink/Math Operations/Trigonometric Function', ...
    subsystemPath + "/SinTheta", 'Operator', 'sin', ...
    'Position', [390, 180, 440, 210]);
add_block('simulink/Math Operations/Product', subsystemPath + "/XDot", ...
    'Inputs', '**', 'Position', [485, 45, 520, 75]);
add_block('simulink/Math Operations/Product', subsystemPath + "/YDot", ...
    'Inputs', '**', 'Position', [485, 220, 520, 250]);
add_block('simulink/Discrete/Discrete-Time Integrator', ...
    subsystemPath + "/XIntegrator", ...
    'gainval', '1', 'InitialCondition', '0', ...
    'SampleTime', num2str(params.sampleTime.plant, '%.15g'), ...
    'Position', [565, 45, 620, 80]);
add_block('simulink/Discrete/Discrete-Time Integrator', ...
    subsystemPath + "/YIntegrator", ...
    'gainval', '1', 'InitialCondition', '0', ...
    'SampleTime', num2str(params.sampleTime.plant, '%.15g'), ...
    'Position', [565, 220, 620, 255]);

addOutport(subsystemPath, 'x', 1, [690, 45, 720, 65]);
addOutport(subsystemPath, 'y', 2, [690, 105, 720, 125]);
addOutport(subsystemPath, 'theta', 3, [690, 165, 720, 185]);
addOutport(subsystemPath, 'wheelLeft', 4, [690, 225, 720, 245]);
addOutport(subsystemPath, 'wheelRight', 5, [690, 285, 720, 305]);

add_line(subsystemPath, 'vCmd/1', 'LeftFromV/1', 'autorouting', 'on');
add_line(subsystemPath, 'wCmd/1', 'LeftFromW/1', 'autorouting', 'on');
add_line(subsystemPath, 'LeftFromV/1', 'WheelLeft/1', 'autorouting', 'on');
add_line(subsystemPath, 'LeftFromW/1', 'WheelLeft/2', 'autorouting', 'on');
add_line(subsystemPath, 'vCmd/1', 'RightFromV/1', 'autorouting', 'on');
add_line(subsystemPath, 'wCmd/1', 'RightFromW/1', 'autorouting', 'on');
add_line(subsystemPath, 'RightFromV/1', 'WheelRight/1', 'autorouting', 'on');
add_line(subsystemPath, 'RightFromW/1', 'WheelRight/2', 'autorouting', 'on');
add_line(subsystemPath, 'wCmd/1', 'ThetaIntegrator/1', 'autorouting', 'on');
add_line(subsystemPath, 'ThetaIntegrator/1', 'CosTheta/1', 'autorouting', 'on');
add_line(subsystemPath, 'ThetaIntegrator/1', 'SinTheta/1', 'autorouting', 'on');
add_line(subsystemPath, 'vCmd/1', 'XDot/1', 'autorouting', 'on');
add_line(subsystemPath, 'CosTheta/1', 'XDot/2', 'autorouting', 'on');
add_line(subsystemPath, 'vCmd/1', 'YDot/1', 'autorouting', 'on');
add_line(subsystemPath, 'SinTheta/1', 'YDot/2', 'autorouting', 'on');
add_line(subsystemPath, 'XDot/1', 'XIntegrator/1', 'autorouting', 'on');
add_line(subsystemPath, 'YDot/1', 'YIntegrator/1', 'autorouting', 'on');
add_line(subsystemPath, 'XIntegrator/1', 'x/1', 'autorouting', 'on');
add_line(subsystemPath, 'YIntegrator/1', 'y/1', 'autorouting', 'on');
add_line(subsystemPath, 'ThetaIntegrator/1', 'theta/1', 'autorouting', 'on');
add_line(subsystemPath, 'WheelLeft/1', 'wheelLeft/1', 'autorouting', 'on');
add_line(subsystemPath, 'WheelRight/1', 'wheelRight/1', 'autorouting', 'on');
end

function addOutport(subsystemPath, name, port, position)
add_block('simulink/Sinks/Out1', subsystemPath + "/" + name, ...
    'Port', num2str(port), 'Position', position);
end

function closeModelIfLoaded(modelName)
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
end
