function modelPath = build_amr_scenario_model_skeleton()
%BUILD_AMR_SCENARIO_MODEL_SKELETON Create the scenario model and loggers.
% Stateflow states, chart data, and chart signal lines are added separately.

projectRoot = fileparts(fileparts(mfilename("fullpath")));
modelDirectory = fullfile(projectRoot, "models", "examples");
modelName = "amr_scenario_supervisor";
modelPath = fullfile(modelDirectory, modelName + ".slx");

if isfile(modelPath)
    error("AMR:ModelAlreadyExists", ...
        "Model already exists and will not be overwritten: %s", modelPath);
end

new_system(modelName);
cleanup = onCleanup(@() closeModelIfLoaded(modelName));

add_block("sflib/Chart", modelName + "/MissionSupervisor", ...
    "Position", [360, 70, 570, 250]);
add_block("simulink/User-Defined Functions/MATLAB Function", ...
    modelName + "/ScenarioEngine", ...
    "Position", [720, 65, 970, 300]);
setScenarioEngineScript(modelName + "/ScenarioEngine");

add_block("simulink/Sources/Constant", modelName + "/ScenarioId", ...
    "Value", "1", "Position", [50, 225, 100, 255]);
add_block("simulink/Sources/Digital Clock", modelName + "/SimulationTime", ...
    "SampleTime", "0.05", "Position", [50, 280, 100, 310]);
add_block("simulink/Discrete/Unit Delay", modelName + "/ModeDelay", ...
    "SampleTime", "0.05", "InitialCondition", "0", ...
    "Position", [620, 20, 665, 50]);

add_line(modelName, "ModeDelay/1", "ScenarioEngine/1", "autorouting", "on");
add_line(modelName, "ScenarioId/1", "ScenarioEngine/2", "autorouting", "on");
add_line(modelName, "SimulationTime/1", "ScenarioEngine/3", "autorouting", "on");

logNames = ["X", "Y", "Theta", "Battery", "V", "W", ...
    "Obstacle", "BatteryLow", "OffRoute", "AtCharger", ...
    "RecoveryComplete", "GoalReached", "EventCode"];
variableNames = ["scenarioXLog", "scenarioYLog", "scenarioThetaLog", ...
    "scenarioBatteryLog", "scenarioVLog", "scenarioWLog", ...
    "scenarioObstacleLog", "scenarioBatteryLowLog", "scenarioOffRouteLog", ...
    "scenarioAtChargerLog", "scenarioRecoveryCompleteLog", ...
    "scenarioGoalReachedLog", "scenarioEventCodeLog"];

for index = 1:numel(logNames)
    row = mod(index - 1, 7);
    column = floor((index - 1) / 7);
    position = [1050 + 180 * column, 25 + 52 * row, ...
        1195 + 180 * column, 55 + 52 * row];
    add_block("simulink/Sinks/To Workspace", ...
        modelName + "/Log" + logNames(index), ...
        "VariableName", variableNames(index), ...
        "SaveFormat", "Timeseries", ...
        "Position", position);
    add_line(modelName, "ScenarioEngine/" + index, ...
        "Log" + logNames(index) + "/1", "autorouting", "on");
end

add_block("simulink/Sinks/To Workspace", modelName + "/LogMissionMode", ...
    "VariableName", "scenarioMissionModeLog", "SaveFormat", "Timeseries", ...
    "Position", [620, 340, 790, 370]);

set_param(modelName, ...
    "SolverType", "Fixed-step", ...
    "Solver", "FixedStepDiscrete", ...
    "FixedStep", "0.05", ...
    "StopTime", "90", ...
    "ReturnWorkspaceOutputs", "on");

save_system(modelName, modelPath);
clear cleanup;
close_system(modelName, 0);
fprintf("Created scenario model skeleton: %s\n", modelPath);
end

function setScenarioEngineScript(blockPath)
root = sfroot;
chart = find(root, "-isa", "Stateflow.EMChart", "Path", blockPath);
chart.Script = sprintf( ...
    "function [x,y,theta,battery,v,w,obstacle,batteryLow,offRoute," + ...
    "atCharger,recoveryComplete,goalReached,eventCode] = " + ...
    "fcn(missionMode,scenarioId,simulationTime)\n" + ...
    "coder.extrinsic('amr.scenarios.scenarioEngineStep');\n" + ...
    "x=0.0; y=0.0; theta=0.0; battery=0.0; v=0.0; w=0.0;\n" + ...
    "obstacle=false; batteryLow=false; offRoute=false; " + ...
    "atCharger=false; recoveryComplete=false; goalReached=false; " + ...
    "eventCode=uint8(0);\n" + ...
    "[x,y,theta,battery,v,w,obstacle,batteryLow,offRoute," + ...
    "atCharger,recoveryComplete,goalReached,eventCode] = " + ...
    "amr.scenarios.scenarioEngineStep(uint8(missionMode)," + ...
    "scenarioId,simulationTime);\n");
end

function closeModelIfLoaded(modelName)
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
end
