function modelPath = build_amr_integrated_system()
%BUILD_AMR_INTEGRATED_SYSTEM Combine the scenario plant and industrial monitor.

projectRoot = fileparts(fileparts(mfilename("fullpath")));
scenarioPath = fullfile(projectRoot, "models", "examples", ...
    "amr_scenario_supervisor.slx");
industrialPath = fullfile(projectRoot, "models", "examples", ...
    "amr_industrial_supervisor.slx");
modelName = "amr_integrated_delivery_system";
modelPath = fullfile(projectRoot, "models", "current", modelName + ".slx");
if isfile(modelPath)
    error("AMR:ModelAlreadyExists", ...
        "Integrated model already exists and will not be overwritten: %s", ...
        modelPath);
end

load_system(scenarioPath);
load_system(industrialPath);
new_system(modelName);
cleanup = onCleanup(@() closeModelIfLoaded(modelName));

add_block("amr_scenario_supervisor/MissionSupervisor", ...
    modelName + "/ScenarioSupervisor", "Position", [360, 80, 560, 250]);
add_block("amr_scenario_supervisor/ScenarioEngine", ...
    modelName + "/NavigationPlant", "Position", [680, 60, 930, 300]);
add_block("amr_industrial_supervisor/IndustrialSupervisor", ...
    modelName + "/IndustrialSupervisor", "Position", [1380, 50, 1680, 360]);
add_block("simulink/User-Defined Functions/MATLAB Function", ...
    modelName + "/SupervisorAdapter", "Position", [1030, 40, 1260, 380]);
setAdapterScript(modelName + "/SupervisorAdapter");

add_block("simulink/Sources/Constant", modelName + "/ScenarioId", ...
    "Value", "1", "Position", [50, 80, 100, 110]);
add_block("simulink/Sources/Digital Clock", modelName + "/SimulationTime", ...
    "SampleTime", "0.05", "Position", [50, 135, 100, 165]);
add_block("simulink/Discrete/Unit Delay", modelName + "/ModeDelay", ...
    "SampleTime", "0.05", "InitialCondition", "0", ...
    "Position", [600, 20, 645, 50]);

add_line(modelName, "ModeDelay/1", "NavigationPlant/1", "autorouting", "on");
add_line(modelName, "ScenarioId/1", "NavigationPlant/2", "autorouting", "on");
add_line(modelName, "SimulationTime/1", "NavigationPlant/3", "autorouting", "on");
for portIndex = 1:6
    add_line(modelName, "NavigationPlant/" + (portIndex + 6), ...
        "ScenarioSupervisor/" + portIndex, "autorouting", "on");
end
add_line(modelName, "ScenarioSupervisor/1", "ModeDelay/1", "autorouting", "on");

adapterSources = [ ...
    "ScenarioId/1", "SimulationTime/1", "NavigationPlant/4", ...
    "NavigationPlant/7", "NavigationPlant/8", "NavigationPlant/9", ...
    "NavigationPlant/10", "NavigationPlant/11", "NavigationPlant/12", ...
    "NavigationPlant/13", "ScenarioSupervisor/1"];
for portIndex = 1:numel(adapterSources)
    add_line(modelName, adapterSources(portIndex), ...
        "SupervisorAdapter/" + portIndex, "autorouting", "on");
end
for portIndex = 1:20
    add_line(modelName, "SupervisorAdapter/" + portIndex, ...
        "IndustrialSupervisor/" + portIndex, "autorouting", "on");
end

addLog(modelName, "NavigationPlant/1", "IntegratedX", "integratedXLog", [1760, 410]);
addLog(modelName, "NavigationPlant/2", "IntegratedY", "integratedYLog", [1760, 450]);
addLog(modelName, "NavigationPlant/3", "IntegratedTheta", ...
    "integratedThetaLog", [1760, 530]);
addLog(modelName, "NavigationPlant/5", "IntegratedV", ...
    "integratedVLog", [1760, 570]);
addLog(modelName, "NavigationPlant/6", "IntegratedW", ...
    "integratedWLog", [1760, 610]);
addLog(modelName, "ScenarioSupervisor/1", "ScenarioMission", ...
    "integratedScenarioMissionLog", [1760, 490]);
industrialLogNames = ["Lifecycle", "Mission", "Navigation", ...
    "Energy", "Safety", "Health"];
industrialVariables = ["integratedLifecycleLog", "integratedMissionLog", ...
    "integratedNavigationLog", "integratedEnergyLog", ...
    "integratedSafetyLog", "integratedHealthLog"];
for portIndex = 1:6
    addLog(modelName, "IndustrialSupervisor/" + portIndex, ...
        industrialLogNames(portIndex), industrialVariables(portIndex), ...
        [1760, 40 + 55 * (portIndex - 1)]);
end

set_param(modelName, "SolverType", "Fixed-step", ...
    "Solver", "FixedStepDiscrete", "FixedStep", "0.05", ...
    "StopTime", "90", "ReturnWorkspaceOutputs", "on");
save_system(modelName, modelPath);
clear cleanup;
close_system(modelName, 0);
fprintf("Created integrated delivery system: %s\n", modelPath);
end

function setAdapterScript(blockPath)
chart = find(sfroot, "-isa", "Stateflow.EMChart", "Path", blockPath);
chart.Script = sprintf( ...
    "function [startRequest,bootComplete,shutdownRequest,emergencyStop," + ...
    "resetRequest,jobAvailable,planReady,plannerFailed,controllerFailed," + ...
    "goalReachedOut,pathInvalid,obstacleSlow,obstacleStop,batteryLowOut," + ...
    "batteryCritical,chargerReached,chargeComplete,localizationHealthy," + ...
    "sensorFresh,actuatorHealthy] = fcn(scenarioId,t,battery,obstacle," + ...
    "batteryLow,offRoute,atCharger,recoveryComplete,goalReached,eventCode," + ...
    "scenarioMissionMode)\n" + ...
    "startRequest = t >= 0.10 && scenarioMissionMode ~= uint8(8);\n" + ...
    "bootComplete = t >= 1.00;\n" + ...
    "shutdownRequest = scenarioMissionMode == uint8(8); emergencyStop = false;\n" + ...
    "resetRequest = recoveryComplete || (scenarioMissionMode == uint8(3) && ~obstacle) || scenarioMissionMode == uint8(7);\n" + ...
    "jobAvailable = t >= 1.20;\n" + ...
    "planReady = scenarioMissionMode == uint8(1) || scenarioMissionMode == uint8(3) || scenarioMissionMode == uint8(4) || scenarioMissionMode == uint8(7);\n" + ...
    "plannerFailed = false; controllerFailed = false;\n" + ...
    "goalReachedOut = goalReached; pathInvalid = obstacle || offRoute;\n" + ...
    "obstacleSlow = eventCode == uint8(6); obstacleStop = obstacle;\n" + ...
    "batteryLowOut = batteryLow; batteryCritical = battery <= 20.0;\n" + ...
    "chargerReached = atCharger;\n" + ...
    "chargeComplete = recoveryComplete && battery >= 89.0;\n" + ...
    "localizationHealthy = ~offRoute; sensorFresh = true; actuatorHealthy = true;\n" + ...
    "if scenarioId < 1, shutdownRequest = true; end\n");
end

function addLog(modelName, source, blockName, variableName, position)
add_block("simulink/Sinks/To Workspace", modelName + "/Log" + blockName, ...
    "VariableName", variableName, "SaveFormat", "Timeseries", ...
    "Position", [position, position + [170, 30]]);
add_line(modelName, source, "Log" + blockName + "/1", "autorouting", "on");
end

function closeModelIfLoaded(modelName)
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
end
