function verification = run_supervisor_verification()
%RUN_SUPERVISOR_VERIFICATION Run the repeatable verification workflow.
%   This runner uses matlab.unittest and scripted-plant simulations because
%   Simulink Test is not installed in the project environment.

scriptFolder = fileparts(mfilename("fullpath"));
projectRoot = fileparts(scriptFolder);
addpath( ...
    fullfile(projectRoot, "src"), ...
    fullfile(projectRoot, "scripts"), ...
    fullfile(projectRoot, "tests", "unit"));

verify_supervisor_requirements();

interfaceTestFile = fullfile( ...
    projectRoot, "tests", "unit", "SupervisorInterfacesTest.m");
interfaceResults = runtests(interfaceTestFile);
assert(all([interfaceResults.Passed]), ...
    "AMR:Supervision:InterfaceTestsFailed", ...
    "%d of %d Supervisor interface tests failed.", ...
    nnz(~[interfaceResults.Passed]), numel(interfaceResults));

layoutTestFile = fullfile( ...
    projectRoot, "tests", "unit", "StateflowGraphicalLayoutTest.m");
layoutResults = runtests(layoutTestFile);
assert(all([layoutResults.Passed]), ...
    "AMR:Supervision:GraphicalLayoutTestsFailed", ...
    "%d of %d Stateflow graphical layout tests failed.", ...
    nnz(~[layoutResults.Passed]), numel(layoutResults));

supervisorModelPath = fullfile(projectRoot, "models", "prototypes", ...
    "amr_mission_supervisor.slx");
scenarioSummary = run_amr_mission_supervisor_scenarios( ...
    ModelPath=supervisorModelPath);
assert(all(scenarioSummary.Passed), ...
    "AMR:Supervision:ScenarioTestsFailed", ...
    "%d of %d Supervisor scenarios failed.", ...
    nnz(~scenarioSummary.Passed), height(scenarioSummary));

verification.requirementsFormatPassed = true;
verification.interfaceTestCount = numel(interfaceResults);
verification.interfaceTestsPassed = nnz([interfaceResults.Passed]);
verification.layoutTestCount = numel(layoutResults);
verification.layoutTestsPassed = nnz([layoutResults.Passed]);
verification.scenarioCount = height(scenarioSummary);
verification.scenariosPassed = nnz(scenarioSummary.Passed);
verification.scenarioSummary = scenarioSummary;
verification.passed = ...
    verification.requirementsFormatPassed && ...
    verification.interfaceTestsPassed == verification.interfaceTestCount && ...
    verification.layoutTestsPassed == verification.layoutTestCount && ...
    verification.scenariosPassed == verification.scenarioCount;

fprintf( ...
    "Supervisor verification: requirements PASS | " + ...
    "interfaces %d/%d | graphical layout %d/%d | scenarios %d/%d.\n", ...
    verification.interfaceTestsPassed, ...
    verification.interfaceTestCount, ...
    verification.layoutTestsPassed, ...
    verification.layoutTestCount, ...
    verification.scenariosPassed, ...
    verification.scenarioCount);
end
