function [playbackData, simulationOutput] = simulate_amr_milestone01()
%SIMULATE_AMR_MILESTONE01 Run the model and return UI-ready column vectors.

scriptDirectory = fileparts(mfilename("fullpath"));
projectDirectory = fileparts(scriptDirectory);
sourceDirectory = fullfile(projectDirectory, "src");
modelFile = fullfile(projectDirectory, "models", "examples", ...
    "amr_milestone01.slx");

addpath(scriptDirectory, sourceDirectory);
parameters = create_default_amr_params();
modelName = "amr_milestone01";
load_system(modelFile);
set_param(modelName, ...
    "SolverType", "Fixed-step", ...
    "Solver", "FixedStepDiscrete", ...
    "FixedStep", num2str(parameters.sampleTime.plant), ...
    "StopTime", num2str(parameters.simulation.stopTime));

simulationOutput = sim(modelName, "ReturnWorkspaceOutputs", "on");

stateLog = simulationOutput.get("stateIdLog");
linearVelocityLog = simulationOutput.get("vCmdLog");
angularVelocityLog = simulationOutput.get("wCmdLog");
xLog = simulationOutput.get("xLog");
yLog = simulationOutput.get("yLog");
headingLog = simulationOutput.get("thetaLog");
leftWheelLog = simulationOutput.get("wheelLeftLog");
rightWheelLog = simulationOutput.get("wheelRightLog");

playbackData = struct( ...
    "time", xLog.Time(:), ...
    "x", localColumn(xLog.Data), ...
    "y", localColumn(yLog.Data), ...
    "heading", localColumn(headingLog.Data), ...
    "stateId", uint8(localColumn(stateLog.Data)), ...
    "linearVelocity", localColumn(linearVelocityLog.Data), ...
    "angularVelocity", localColumn(angularVelocityLog.Data), ...
    "leftWheelSpeed", localColumn(leftWheelLog.Data), ...
    "rightWheelSpeed", localColumn(rightWheelLog.Data), ...
    "parameters", parameters, ...
    "modelFile", modelFile);

signalLengths = [numel(playbackData.x), numel(playbackData.y), ...
    numel(playbackData.heading), numel(playbackData.stateId), ...
    numel(playbackData.linearVelocity), numel(playbackData.angularVelocity), ...
    numel(playbackData.leftWheelSpeed), numel(playbackData.rightWheelSpeed)];
assert(all(signalLengths == numel(playbackData.time)), ...
    "AMR:PlaybackLengthMismatch", ...
    "All playback signals must have the same number of samples.");
end

function value = localColumn(value)
value = reshape(squeeze(value), [], 1);
end
