function profile = graphicalLayoutProfile()
%GRAPHICALLAYOUTPROFILE Validated defaults for all AMR Stateflow charts.
%   This is the single source for Subchart local origin, persisted page,
%   and readable viewport thresholds. New charts use the same profile as
%   the accepted Mission Supervisor v07 layout.

profile = struct( ...
    "LocalStart", [100 120], ...
    "LocalStartWithTopReturnLane", [100 200], ...
    "LocalMinimumRange", [80 100], ...
    "LocalMaximumRange", [120 200], ...
    "MinimumPagePadding", 60, ...
    "TargetPageUtilization", [0.90 0.82], ...
    "TargetViewportFraction", [0.90 0.76], ...
    "MaximumViewportMagnification", 3.5, ...
    "MinimumContentAxisFraction", 0.70, ...
    "MaximumContentFraction", [0.93 0.82], ...
    "StateFontSize", 10, ...
    "TransitionFontSize", 9, ...
    "MinimumHorizontalStateGap", 80, ...
    "MinimumVerticalStateGap", 110);
end
