function report = inspectGraphicalLayout(modelInput, chartInput)
%INSPECTGRAPHICALLAYOUT Inspect the graphical quality of a Stateflow chart.
%   REPORT = amr.stateflow.inspectGraphicalLayout(MODEL, CHART) loads MODEL
%   when necessary and inspects CHART without changing or saving the model.
%   MODEL is a model name or model file path. CHART is a Stateflow.Chart
%   object, a chart name, or a full chart path.
%
%   Hard violations cover sibling-state overlap, Stateflow-reported bad
%   intersections, the NavigationRegion row contract, fonts, transition
%   label overlap, transition paths through unrelated states, and crowded
%   outgoing transition endpoints. Routing diagnostics additionally inspect
%   the complete routing inventory and approximate path geometry. State text
%   fit is an advisory estimate because Stateflow does not expose the
%   rendered state-label extent.

narginchk(1, 2);
if nargin < 2
    chartInput = "MissionSupervisor";
end

mustBeTextScalar(modelInput);
[modelName, closeWhenDone] = ensureModelLoaded(string(modelInput));
cleanup = onCleanup(@() closeOwnedModel(modelName, closeWhenDone));
chart = resolveChart(modelName, chartInput);

rules = graphicalRules();
states = chart.find("-isa", "Stateflow.State");
transitions = chart.find("-isa", "Stateflow.Transition");
stateGeometry = collectStateGeometry(states);
transitionGeometry = collectTransitionGeometry(transitions);

badIntersections = inspectBadIntersections( ...
    states, stateGeometry);
stateOverlaps = inspectStateOverlaps(stateGeometry, rules);
navigationRegion = inspectNavigationRegion(stateGeometry, rules);
fontViolations = inspectFonts( ...
    chart, states, transitions, stateGeometry, transitionGeometry, rules);
labelStateOverlaps = inspectLabelStateOverlaps( ...
    transitionGeometry, stateGeometry, rules);
labelLabelOverlaps = inspectLabelLabelOverlaps( ...
    transitionGeometry, rules);
transitionStateCrossings = inspectTransitionStateCrossings( ...
    transitions, transitionGeometry, stateGeometry, rules);
outgoingEndpointSpacing = inspectOutgoingEndpointSpacing( ...
    transitions, transitionGeometry, rules);
stateTextFitAdvisories = inspectStateTextFit( ...
    states, stateGeometry, rules);
routingInventory = buildRoutingInventory( ...
    transitionGeometry, stateGeometry, rules);
routingCompleteness = inspectRoutingCompleteness( ...
    transitions, transitionGeometry);
completePathOverlaps = inspectCompletePathOverlaps( ...
    transitionGeometry, rules);
midPointStateIntersections = inspectMidPointStateIntersections( ...
    transitionGeometry, stateGeometry, rules);
selfLoopOClockViolations = inspectSelfLoopOClockSeparation( ...
    transitions, transitionGeometry, rules);
outerLaneSpacingViolations = inspectOuterLaneSpacing( ...
    transitionGeometry, stateGeometry, rules);
outerLaneEnvelopeClearanceViolations = ...
    inspectOuterLaneEnvelopeClearance( ...
    transitionGeometry, stateGeometry, rules);
excessiveOuterLaneClearanceViolations = ...
    inspectExcessiveOuterLaneClearance( ...
    transitionGeometry, stateGeometry, rules);
scopeCanvasInventory = buildScopeCanvasInventory( ...
    transitionGeometry, stateGeometry);
scopeCanvasBalanceViolations = inspectScopeCanvasBalance( ...
    scopeCanvasInventory, rules);
bidirectionalOuterDetourViolations = ...
    inspectBidirectionalOuterDetours( ...
    transitionGeometry, stateGeometry, rules);
shortTransitionStraightnessViolations = ...
    inspectShortTransitionStraightness( ...
    transitions, transitionGeometry, stateGeometry, rules);
bidirectionalTransitionViolations = ...
    inspectBidirectionalTransitionSeparation( ...
    transitionGeometry, rules);
pathShapeViolations = inspectApproximatePathShapes( ...
    transitionGeometry, stateGeometry, rules);
labelPathOverlaps = inspectLabelPathOverlaps( ...
    transitionGeometry, rules);
pathPathInteractions = inspectPathPathInteractions( ...
    transitionGeometry, rules);

hardViolations = [
    badIntersections
    stateOverlaps
    navigationRegion
    fontViolations
    labelStateOverlaps
    labelLabelOverlaps
    transitionStateCrossings
    outgoingEndpointSpacing
    ];
routingViolations = [
    routingCompleteness
    completePathOverlaps
    midPointStateIntersections
    selfLoopOClockViolations
    outerLaneSpacingViolations
    outerLaneEnvelopeClearanceViolations
    excessiveOuterLaneClearanceViolations
    scopeCanvasBalanceViolations
    bidirectionalOuterDetourViolations
    shortTransitionStraightnessViolations
    bidirectionalTransitionViolations
    pathShapeViolations
    labelPathOverlaps
    pathPathInteractions
    ];
exactRoutingViolations = [
    routingCompleteness
    midPointStateIntersections
    selfLoopOClockViolations
    excessiveOuterLaneClearanceViolations
    scopeCanvasBalanceViolations
    bidirectionalOuterDetourViolations
    ];
approximateRoutingViolations = [
    completePathOverlaps
    outerLaneSpacingViolations
    outerLaneEnvelopeClearanceViolations
    shortTransitionStraightnessViolations
    bidirectionalTransitionViolations
    pathShapeViolations
    labelPathOverlaps
    pathPathInteractions
    ];

report = struct;
report.Model = modelName;
report.Chart = string(chart.Path);
report.StateCount = uint32(numel(states));
report.TransitionCount = uint32(numel(transitions));
report.Rules = rules;
report.BadIntersections = badIntersections;
report.StateOverlaps = stateOverlaps;
report.NavigationRegion = navigationRegion;
report.FontViolations = fontViolations;
report.LabelStateOverlaps = labelStateOverlaps;
report.LabelLabelOverlaps = labelLabelOverlaps;
report.TransitionStateCrossings = transitionStateCrossings;
report.OutgoingEndpointSpacing = outgoingEndpointSpacing;
report.StateTextFitAdvisories = stateTextFitAdvisories;
report.HardViolations = hardViolations;
report.HardViolationCount = uint32(height(hardViolations));
report.AdvisoryCount = uint32(height(stateTextFitAdvisories));
report.Passed = isempty(hardViolations);
report.PathApproximation = ...
    "SourceEndpoint-to-MidPoint-to-DestinationEndpoint line segments";
report.HardDiagnostic = formatDiagnostic(hardViolations, ...
    "No hard graphical layout violations.");
report.AdvisoryDiagnostic = formatDiagnostic(stateTextFitAdvisories, ...
    "No state text-fit advisories.");
report.RoutingInventory = routingInventory;
report.RoutingCompletenessViolations = routingCompleteness;
report.RoutingCompletenessViolationCount = ...
    uint32(height(routingCompleteness));
report.CompletePathOverlaps = completePathOverlaps;
report.CompletePathOverlapCount = uint32(height(completePathOverlaps));
report.MidPointStateIntersections = midPointStateIntersections;
report.MidPointStateIntersectionCount = ...
    uint32(height(midPointStateIntersections));
report.SelfLoopOClockViolations = selfLoopOClockViolations;
report.SelfLoopOClockViolationCount = ...
    uint32(height(selfLoopOClockViolations));
report.OuterLaneSpacingViolations = outerLaneSpacingViolations;
report.OuterLaneSpacingViolationCount = ...
    uint32(height(outerLaneSpacingViolations));
report.OuterLaneEnvelopeClearanceViolations = ...
    outerLaneEnvelopeClearanceViolations;
report.OuterLaneEnvelopeClearanceViolationCount = ...
    uint32(height(outerLaneEnvelopeClearanceViolations));
report.ExcessiveOuterLaneClearanceViolations = ...
    excessiveOuterLaneClearanceViolations;
report.ExcessiveOuterLaneClearanceViolationCount = ...
    uint32(height(excessiveOuterLaneClearanceViolations));
report.ScopeCanvasInventory = scopeCanvasInventory;
report.ScopeCanvasBalanceViolations = scopeCanvasBalanceViolations;
report.ScopeCanvasBalanceViolationCount = ...
    uint32(height(scopeCanvasBalanceViolations));
report.BidirectionalOuterDetourViolations = ...
    bidirectionalOuterDetourViolations;
report.BidirectionalOuterDetourViolationCount = ...
    uint32(height(bidirectionalOuterDetourViolations));
report.ShortTransitionStraightnessViolations = ...
    shortTransitionStraightnessViolations;
report.ShortTransitionStraightnessViolationCount = ...
    uint32(height(shortTransitionStraightnessViolations));
report.BidirectionalTransitionViolations = ...
    bidirectionalTransitionViolations;
report.BidirectionalTransitionViolationCount = ...
    uint32(height(bidirectionalTransitionViolations));
report.PathShapeViolations = pathShapeViolations;
report.PathShapeViolationCount = uint32(height(pathShapeViolations));
report.LabelPathOverlaps = labelPathOverlaps;
report.LabelPathOverlapCount = uint32(height(labelPathOverlaps));
report.PathPathCrossingOrPartialOverlaps = pathPathInteractions;
report.PathPathCrossingOrPartialOverlapCount = ...
    uint32(height(pathPathInteractions));
report.RoutingViolations = routingViolations;
report.RoutingViolationCount = uint32(height(routingViolations));
report.RoutingPassed = isempty(routingViolations);
report.ExactRoutingViolations = exactRoutingViolations;
report.ExactRoutingViolationCount = ...
    uint32(height(exactRoutingViolations));
report.ExactRoutingPassed = isempty(exactRoutingViolations);
report.ApproximateRoutingViolations = approximateRoutingViolations;
report.ApproximateRoutingViolationCount = ...
    uint32(height(approximateRoutingViolations));
report.RoutingDiagnostic = formatDiagnostic(routingViolations, ...
    "No approximate transition-routing violations.");
report.RoutingLimitations = [
    "Stateflow exposes endpoints, one midpoint, and O'Clock values, " + ...
    "but not the rendered spline or all editor control points."
    "Path overlap, lane separation, straightness, and S-shape checks " + ...
    "therefore use two line segments and are conservative approximations."
    "Label-path and path-path checks use inset and endpoint allowances, " + ...
    "but rendered Stateflow splines can still create false positives."
    "The API does not reveal whether a valid MidPoint or O'Clock value " + ...
    "was assigned explicitly by a layout specification."
    ];

% Keep the cleanup object alive until the report is complete.
if isempty(cleanup)
    error("AMR:Stateflow:UnexpectedCleanupState", ...
        "The model cleanup guard was not created.");
end
end

function rules = graphicalRules()
rules = struct;
rules.GeometryTolerancePixels = 2;
rules.MinimumHorizontalGapPixels = 80;
rules.MinimumVerticalGapPixels = 110;
rules.MinimumOutgoingEndpointGapPixels = 30;
rules.StateFontSize = 10;
rules.TransitionFontSize = 9;
rules.TextWidthFactor = 0.47;
rules.TextLineHeightFactor = 1.35;
rules.TextHorizontalPaddingPixels = 18;
rules.TextVerticalPaddingPixels = 12;
rules.NavigationRegionName = "NavigationRegion";
rules.NavigationNormalRow = ["NavIdle", "Planning", "Tracking"];
rules.NavigationExceptionRow = ["NavFailed", "Recovery", "Replanning"];
rules.RoutingSampleCount = 31;
rules.CompletePathOverlapTolerancePixels = 4;
rules.CompletePathLengthRatioTolerance = 0.05;
rules.MinimumSelfLoopOClockSeparationHours = 2;
rules.OuterLaneDetectionMarginPixels = 8;
rules.MinimumOuterLaneGapPixels = 40;
rules.MinimumOuterLaneEnvelopeClearancePixels = 40;
rules.MaximumOuterLaneEnvelopeClearancePixels = 180;
rules.MinimumScopeStateBBoxUtilization = 0.50;
rules.MaximumScopeCanvasExpansionPixels = 180;
rules.MaximumBidirectionalEnvelopeExcursionPixels = 120;
rules.MaximumBidirectionalDetourRatio = 2.20;
rules.ShortAdjacentStateGapPixels = 200;
rules.ShortTransitionMaximumLengthPixels = 450;
rules.ShortTransitionMaximumDeviationPixels = 20;
rules.ShortTransitionMaximumLengthRatio = 1.10;
rules.MinimumBidirectionalSeparationPixels = 30;
rules.MinimumSelfLoopSpanPixels = 40;
rules.MaximumShortPathDetourRatio = 1.60;
rules.BacktrackingCosineThreshold = -0.50;
rules.LabelPathInsetPixels = 3;
rules.PathInteractionEndpointAllowancePixels = 8;
rules.MinimumPartialPathOverlapPixels = 12;
end

function [modelName, closeWhenDone] = ensureModelLoaded(modelInput)
[~, baseName, extension] = fileparts(modelInput);
if strlength(baseName) == 0
    baseName = modelInput;
end
modelName = string(baseName);
closeWhenDone = ~bdIsLoaded(modelName);

if closeWhenDone
    if strlength(extension) == 0 && ~contains(modelInput, filesep)
        load_system(char(modelName));
    else
        modelHandle = load_system(char(modelInput));
        modelName = string(get_param(modelHandle, "Name"));
    end
end
end

function closeOwnedModel(modelName, closeWhenDone)
if closeWhenDone && bdIsLoaded(modelName) && ...
        strcmp(get_param(modelName, "Dirty"), "off")
    close_system(modelName, 0);
end
end

function chart = resolveChart(modelName, chartInput)
root = sfroot;
if isa(chartInput, "Stateflow.Chart")
    chart = chartInput;
    if ~startsWith(string(chart.Path), modelName + "/")
        error("AMR:Stateflow:ChartModelMismatch", ...
            "Chart '%s' does not belong to model '%s'.", ...
            chart.Path, modelName);
    end
    return
end

mustBeTextScalar(chartInput);
selector = string(chartInput);
if startsWith(selector, modelName + "/")
    chartPath = selector;
else
    chartPath = modelName + "/" + selector;
end

matches = root.find( ...
    "-isa", "Stateflow.Chart", "Path", char(chartPath));
if isempty(matches)
    matches = findChartsByName(root, modelName, selector);
end
if numel(matches) ~= 1
    error("AMR:Stateflow:ChartNotUnique", ...
        "Expected one chart for selector '%s' in model '%s'; found %d.", ...
        selector, modelName, numel(matches));
end
chart = matches(1);
end

function matches = findChartsByName(root, modelName, selector)
allCharts = root.find("-isa", "Stateflow.Chart");
isMatch = false(size(allCharts));
for index = 1:numel(allCharts)
    chartPath = string(allCharts(index).Path);
    isMatch(index) = startsWith(chartPath, modelName + "/") && ...
        string(allCharts(index).Name) == selector;
end
matches = allCharts(isMatch);
end

function geometry = collectStateGeometry(states)
stateCount = numel(states);
geometry = struct;
geometry.Key = strings(stateCount, 1);
geometry.ParentKey = strings(stateCount, 1);
geometry.ParentDisplay = strings(stateCount, 1);
geometry.SubviewerKey = strings(stateCount, 1);
geometry.SubviewerDisplay = strings(stateCount, 1);
geometry.Name = strings(stateCount, 1);
geometry.Display = strings(stateCount, 1);
geometry.Position = zeros(stateCount, 4);
geometry.SSId = zeros(stateCount, 1);

for index = 1:stateCount
    parent = states(index).getParent;
    geometry.Key(index) = objectKey(states(index));
    geometry.ParentKey(index) = objectKey(parent);
    geometry.ParentDisplay(index) = objectDisplay(parent);
    geometry.SubviewerKey(index) = objectKey(states(index).Subviewer);
    geometry.SubviewerDisplay(index) = ...
        objectDisplay(states(index).Subviewer);
    geometry.Name(index) = string(states(index).Name);
    geometry.SSId(index) = double(states(index).SSIdNumber);
    geometry.Display(index) = geometry.Name(index) + ...
        " [SSID " + string(geometry.SSId(index)) + "]";
    geometry.Position(index, :) = double(states(index).Position);
end
end

function geometry = collectTransitionGeometry(transitions)
transitionCount = numel(transitions);
geometry = struct;
geometry.Key = strings(transitionCount, 1);
geometry.ParentKey = strings(transitionCount, 1);
geometry.ParentDisplay = strings(transitionCount, 1);
geometry.SubviewerKey = strings(transitionCount, 1);
geometry.SubviewerDisplay = strings(transitionCount, 1);
geometry.SourceKey = strings(transitionCount, 1);
geometry.DestinationKey = strings(transitionCount, 1);
geometry.Display = strings(transitionCount, 1);
geometry.Label = strings(transitionCount, 1);
geometry.LabelPosition = zeros(transitionCount, 4);
geometry.SourceEndpoint = zeros(transitionCount, 2);
geometry.MidPoint = zeros(transitionCount, 2);
geometry.DestinationEndpoint = zeros(transitionCount, 2);
geometry.SourceOClock = zeros(transitionCount, 1);
geometry.DestinationOClock = zeros(transitionCount, 1);
geometry.SSId = zeros(transitionCount, 1);

for index = 1:transitionCount
    transition = transitions(index);
    parent = transition.getParent;
    geometry.Key(index) = objectKey(transition);
    geometry.ParentKey(index) = objectKey(parent);
    geometry.ParentDisplay(index) = objectDisplay(parent);
    geometry.SubviewerKey(index) = objectKey(transition.Subviewer);
    geometry.SubviewerDisplay(index) = ...
        objectDisplay(transition.Subviewer);
    geometry.SourceKey(index) = objectKey(transition.Source);
    geometry.DestinationKey(index) = objectKey(transition.Destination);
    geometry.Label(index) = string(transition.LabelString);
    geometry.SSId(index) = double(transition.SSIdNumber);
    geometry.Display(index) = transitionDisplay(transition);
    geometry.LabelPosition(index, :) = double(transition.LabelPosition);
    geometry.SourceEndpoint(index, :) = double(transition.SourceEndpoint);
    geometry.MidPoint(index, :) = double(transition.MidPoint);
    geometry.DestinationEndpoint(index, :) = ...
        double(transition.DestinationEndpoint);
    geometry.SourceOClock(index) = double(transition.SourceOClock);
    geometry.DestinationOClock(index) = ...
        double(transition.DestinationOClock);
end
end

function violations = inspectBadIntersections(states, geometry)
collector = createCollector(numel(states));
for index = 1:numel(states)
    if logical(states(index).BadIntersection)
        collector = appendViolation(collector, ...
            "BadIntersection", geometry.ParentDisplay(index), ...
            geometry.Display(index), "", 1, 0, ...
            "Stateflow.State.BadIntersection is true.");
    end
end
violations = finishCollector(collector);
end

function violations = inspectStateOverlaps(geometry, rules)
stateCount = numel(geometry.Key);
collector = createCollector(stateCount * max(stateCount - 1, 0) / 2);
for firstIndex = 1:stateCount
    for secondIndex = firstIndex + 1:stateCount
        if geometry.ParentKey(firstIndex) ~= ...
                geometry.ParentKey(secondIndex)
            continue
        end
        [overlapWidth, overlapHeight] = rectangleOverlap( ...
            geometry.Position(firstIndex, :), ...
            geometry.Position(secondIndex, :));
        if overlapWidth > rules.GeometryTolerancePixels && ...
                overlapHeight > rules.GeometryTolerancePixels
            collector = appendViolation(collector, ...
                "StateOverlap", geometry.ParentDisplay(firstIndex), ...
                geometry.Display(firstIndex), ...
                geometry.Display(secondIndex), ...
                overlapWidth * overlapHeight, 0, ...
                sprintf([ ...
                'First rectangle %s; second rectangle %s; ' ...
                'overlap %.1f by %.1f pixels.'], ...
                mat2str(geometry.Position(firstIndex, :), 5), ...
                mat2str(geometry.Position(secondIndex, :), 5), ...
                overlapWidth, overlapHeight));
        end
    end
end
violations = finishCollector(collector);
end

function violations = inspectNavigationRegion(geometry, rules)
collector = createCollector(32);
regionMatches = find(geometry.Name == rules.NavigationRegionName);
if numel(regionMatches) ~= 1
    collector = appendViolation(collector, ...
        "NavigationRegion", "", rules.NavigationRegionName, "", ...
        numel(regionMatches), 1, ...
        "Expected exactly one NavigationRegion state.");
    violations = finishCollector(collector);
    return
end

regionIndex = regionMatches(1);
childMask = geometry.ParentKey == geometry.Key(regionIndex);
requiredNames = [
    rules.NavigationNormalRow
    rules.NavigationExceptionRow
    ];
childIndices = zeros(size(requiredNames));
for index = 1:numel(requiredNames)
    matches = find(childMask & geometry.Name == requiredNames(index));
    if isscalar(matches)
        childIndices(index) = matches;
    else
        collector = appendViolation(collector, ...
            "NavigationRegion", geometry.Display(regionIndex), ...
            requiredNames(index), "", numel(matches), 1, ...
            "Expected exactly one direct child with this name.");
    end
end

if all(childIndices > 0)
    normalIndices = childIndices(1, :);
    exceptionIndices = childIndices(2, :);
    collector = inspectHorizontalRow(collector, geometry, ...
        normalIndices, "normal", rules);
    collector = inspectHorizontalRow(collector, geometry, ...
        exceptionIndices, "exception", rules);
    for column = 1:size(childIndices, 2)
        topIndex = normalIndices(column);
        bottomIndex = exceptionIndices(column);
        topPosition = geometry.Position(topIndex, :);
        bottomPosition = geometry.Position(bottomIndex, :);
        verticalGap = bottomPosition(2) - ...
            (topPosition(2) + topPosition(4));
        if verticalGap < rules.MinimumVerticalGapPixels
            collector = appendViolation(collector, ...
                "NavigationVerticalGap", ...
                geometry.Display(regionIndex), ...
                geometry.Display(topIndex), ...
                geometry.Display(bottomIndex), verticalGap, ...
                rules.MinimumVerticalGapPixels, ...
                sprintf("Column %d vertical gap is %.1f pixels.", ...
                column, verticalGap));
        end
    end
end
violations = finishCollector(collector);
end

function collector = inspectHorizontalRow( ...
        collector, geometry, rowIndices, rowName, rules)
for column = 1:numel(rowIndices) - 1
    leftIndex = rowIndices(column);
    rightIndex = rowIndices(column + 1);
    leftPosition = geometry.Position(leftIndex, :);
    rightPosition = geometry.Position(rightIndex, :);
    horizontalGap = rightPosition(1) - ...
        (leftPosition(1) + leftPosition(3));
    if horizontalGap < rules.MinimumHorizontalGapPixels
        collector = appendViolation(collector, ...
            "NavigationHorizontalGap", ...
            geometry.ParentDisplay(leftIndex), ...
            geometry.Display(leftIndex), geometry.Display(rightIndex), ...
            horizontalGap, rules.MinimumHorizontalGapPixels, ...
            sprintf("%s row gap is %.1f pixels.", ...
            rowName, horizontalGap));
    end
end
end

function violations = inspectFonts( ...
        chart, states, transitions, stateGeometry, ...
        transitionGeometry, rules)
collector = createCollector(2 + numel(states) + numel(transitions));
chartStateFontSize = double(chart.StateFont.Size);
chartTransitionFontSize = double(chart.TransitionFont.Size);
if chartStateFontSize ~= rules.StateFontSize
    collector = appendViolation(collector, ...
        "StateFont", string(chart.Path), "Chart StateFont", "", ...
        chartStateFontSize, rules.StateFontSize, ...
        "Chart.StateFont.Size does not match the graphical standard.");
end
if chartTransitionFontSize ~= rules.TransitionFontSize
    collector = appendViolation(collector, ...
        "TransitionFont", string(chart.Path), ...
        "Chart TransitionFont", "", chartTransitionFontSize, ...
        rules.TransitionFontSize, ...
        "Chart.TransitionFont.Size does not match the graphical standard.");
end

for index = 1:numel(states)
    fontSize = double(states(index).FontSize);
    if fontSize ~= rules.StateFontSize
        collector = appendViolation(collector, ...
            "StateFont", stateGeometry.ParentDisplay(index), ...
            stateGeometry.Display(index), "", fontSize, ...
            rules.StateFontSize, ...
            "State.FontSize does not match the graphical standard.");
    end
end
for index = 1:numel(transitions)
    fontSize = double(transitions(index).FontSize);
    if fontSize ~= rules.TransitionFontSize
        collector = appendViolation(collector, ...
            "TransitionFont", ...
            transitionGeometry.ParentDisplay(index), ...
            transitionGeometry.Display(index), "", fontSize, ...
            rules.TransitionFontSize, ...
            "Transition.FontSize does not match the graphical standard.");
    end
end
violations = finishCollector(collector);
end

function violations = inspectLabelStateOverlaps( ...
        transitionGeometry, stateGeometry, rules)
transitionCount = numel(transitionGeometry.Key);
stateCount = numel(stateGeometry.Key);
collector = createCollector(transitionCount * stateCount);
for transitionIndex = 1:transitionCount
    if strlength(strtrim(transitionGeometry.Label(transitionIndex))) == 0
        continue
    end
    labelPosition = transitionGeometry.LabelPosition(transitionIndex, :);
    for stateIndex = 1:stateCount
        if transitionGeometry.ParentKey(transitionIndex) ~= ...
                stateGeometry.ParentKey(stateIndex)
            continue
        end
        [overlapWidth, overlapHeight] = rectangleOverlap( ...
            labelPosition, stateGeometry.Position(stateIndex, :));
        if overlapWidth > rules.GeometryTolerancePixels && ...
                overlapHeight > rules.GeometryTolerancePixels
            relation = labelStateRelation( ...
                transitionGeometry, transitionIndex, ...
                stateGeometry.Key(stateIndex));
            collector = appendViolation(collector, ...
                "LabelStateOverlap", ...
                transitionGeometry.ParentDisplay(transitionIndex), ...
                transitionGeometry.Display(transitionIndex), ...
                stateGeometry.Display(stateIndex), ...
                overlapWidth * overlapHeight, 0, ...
                sprintf([ ...
                'Relation=%s; label rectangle %s; state rectangle %s; ' ...
                'overlap %.1f by %.1f pixels.'], ...
                relation, mat2str(labelPosition, 5), ...
                mat2str(stateGeometry.Position(stateIndex, :), 5), ...
                overlapWidth, overlapHeight));
        end
    end
end
violations = finishCollector(collector);
end

function violations = inspectLabelLabelOverlaps(transitionGeometry, rules)
transitionCount = numel(transitionGeometry.Key);
collector = createCollector( ...
    transitionCount * max(transitionCount - 1, 0) / 2);
for firstIndex = 1:transitionCount
    if strlength(strtrim(transitionGeometry.Label(firstIndex))) == 0
        continue
    end
    for secondIndex = firstIndex + 1:transitionCount
        if transitionGeometry.ParentKey(firstIndex) ~= ...
                transitionGeometry.ParentKey(secondIndex) || ...
                strlength(strtrim( ...
                transitionGeometry.Label(secondIndex))) == 0
            continue
        end
        [overlapWidth, overlapHeight] = rectangleOverlap( ...
            transitionGeometry.LabelPosition(firstIndex, :), ...
            transitionGeometry.LabelPosition(secondIndex, :));
        if overlapWidth > rules.GeometryTolerancePixels && ...
                overlapHeight > rules.GeometryTolerancePixels
            collector = appendViolation(collector, ...
                "LabelLabelOverlap", ...
                transitionGeometry.ParentDisplay(firstIndex), ...
                transitionGeometry.Display(firstIndex), ...
                transitionGeometry.Display(secondIndex), ...
                overlapWidth * overlapHeight, 0, ...
                sprintf([ ...
                'First label rectangle %s; second label rectangle %s; ' ...
                'overlap %.1f by %.1f pixels.'], ...
                mat2str( ...
                transitionGeometry.LabelPosition(firstIndex, :), 5), ...
                mat2str( ...
                transitionGeometry.LabelPosition(secondIndex, :), 5), ...
                overlapWidth, overlapHeight));
        end
    end
end
violations = finishCollector(collector);
end

function violations = inspectTransitionStateCrossings( ...
        transitions, transitionGeometry, stateGeometry, rules)
transitionCount = numel(transitions);
stateCount = numel(stateGeometry.Key);
collector = createCollector(transitionCount * stateCount);
for transitionIndex = 1:transitionCount
    pathPoints = [
        transitionGeometry.SourceEndpoint(transitionIndex, :)
        transitionGeometry.MidPoint(transitionIndex, :)
        transitionGeometry.DestinationEndpoint(transitionIndex, :)
        ];
    if any(~isfinite(pathPoints), "all")
        collector = appendViolation(collector, ...
            "TransitionGeometry", ...
            transitionGeometry.ParentDisplay(transitionIndex), ...
            transitionGeometry.Display(transitionIndex), "", NaN, 0, ...
            "Transition endpoint or midpoint is not finite.");
        continue
    end
    sourceKey = objectKey(transitions(transitionIndex).Source);
    destinationKey = objectKey(transitions(transitionIndex).Destination);
    for stateIndex = 1:stateCount
        if transitionGeometry.ParentKey(transitionIndex) ~= ...
                stateGeometry.ParentKey(stateIndex) || ...
                stateGeometry.Key(stateIndex) == sourceKey || ...
                stateGeometry.Key(stateIndex) == destinationKey
            continue
        end
        testRectangle = insetRectangle( ...
            stateGeometry.Position(stateIndex, :), ...
            rules.GeometryTolerancePixels);
        crossesState = segmentIntersectsRectangle( ...
            pathPoints(1, :), pathPoints(2, :), testRectangle) || ...
            segmentIntersectsRectangle( ...
            pathPoints(2, :), pathPoints(3, :), testRectangle);
        if crossesState
            collector = appendViolation(collector, ...
                "TransitionStateCrossing", ...
                transitionGeometry.ParentDisplay(transitionIndex), ...
                transitionGeometry.Display(transitionIndex), ...
                stateGeometry.Display(stateIndex), 1, 0, ...
                sprintf([ ...
                'Path [source; midpoint; destination] %s crosses ' ...
                'unrelated state rectangle %s.'], ...
                mat2str(pathPoints, 5), ...
                mat2str(stateGeometry.Position(stateIndex, :), 5)));
        end
    end
end
violations = finishCollector(collector);
end

function violations = inspectOutgoingEndpointSpacing( ...
        transitions, transitionGeometry, rules)
transitionCount = numel(transitions);
collector = createCollector( ...
    transitionCount * max(transitionCount - 1, 0) / 2);
for firstIndex = 1:transitionCount
    if isempty(transitions(firstIndex).Source) || ...
            ~isa(transitions(firstIndex).Source, "Stateflow.State")
        continue
    end
    for secondIndex = firstIndex + 1:transitionCount
        if transitionGeometry.SourceKey(firstIndex) ~= ...
                transitionGeometry.SourceKey(secondIndex)
            continue
        end
        endpointDistance = norm( ...
            transitionGeometry.SourceEndpoint(firstIndex, :) - ...
            transitionGeometry.SourceEndpoint(secondIndex, :));
        if endpointDistance + rules.GeometryTolerancePixels < ...
                rules.MinimumOutgoingEndpointGapPixels
            collector = appendViolation(collector, ...
                "OutgoingEndpointSpacing", ...
                transitionGeometry.ParentDisplay(firstIndex), ...
                transitionGeometry.Display(firstIndex), ...
                transitionGeometry.Display(secondIndex), ...
                endpointDistance, ...
                rules.MinimumOutgoingEndpointGapPixels, ...
                sprintf( ...
                'Source endpoints %s and %s are %.1f pixels apart.', ...
                mat2str( ...
                transitionGeometry.SourceEndpoint(firstIndex, :), 5), ...
                mat2str( ...
                transitionGeometry.SourceEndpoint(secondIndex, :), 5), ...
                endpointDistance));
        end
    end
end
violations = finishCollector(collector);
end

function advisories = inspectStateTextFit(states, geometry, rules)
collector = createCollector(numel(states));
for index = 1:numel(states)
    label = replace(string(states(index).LabelString), ...
        sprintf("\t"), "    ");
    labelLines = splitlines(label);
    maximumCharacters = max(strlength(labelLines));
    fontSize = double(states(index).FontSize);
    estimatedWidth = double(maximumCharacters) * ...
        rules.TextWidthFactor * fontSize + ...
        rules.TextHorizontalPaddingPixels;
    estimatedHeight = numel(labelLines) * ...
        rules.TextLineHeightFactor * fontSize + ...
        rules.TextVerticalPaddingPixels;
    position = geometry.Position(index, :);
    widthMargin = position(3) - estimatedWidth;
    heightMargin = position(4) - estimatedHeight;
    minimumMargin = min(widthMargin, heightMargin);
    if minimumMargin < -rules.GeometryTolerancePixels
        collector = appendViolation(collector, ...
            "StateTextFitAdvisory", geometry.ParentDisplay(index), ...
            geometry.Display(index), "", minimumMargin, 0, ...
            sprintf([ ...
            'State is %.1f by %.1f pixels; estimated text need is ' ...
            '%.1f by %.1f pixels.'], ...
            position(3), position(4), estimatedWidth, estimatedHeight));
    end
end
advisories = finishCollector(collector);
end

function inventory = buildRoutingInventory( ...
        transitionGeometry, stateGeometry, rules)
transitionCount = numel(transitionGeometry.Key);
isDefault = false(transitionCount, 1);
isSelfLoop = false(transitionCount, 1);
geometryComplete = false(transitionCount, 1);
pathLength = zeros(transitionCount, 1);
directLength = zeros(transitionCount, 1);
outerLaneSide = strings(transitionCount, 1);
outerLaneCoordinate = nan(transitionCount, 1);
outerLaneEnvelopeClearance = nan(transitionCount, 1);

for index = 1:transitionCount
    pathPoints = transitionPathPoints(transitionGeometry, index);
    isDefault(index) = transitionGeometry.SourceKey(index) == "<none>";
    isSelfLoop(index) = ~isDefault(index) && ...
        transitionGeometry.SourceKey(index) == ...
        transitionGeometry.DestinationKey(index);
    geometryComplete(index) = routingGeometryIsComplete( ...
        transitionGeometry, index);
    pathLength(index) = approximatePathLength(pathPoints);
    directLength(index) = norm(pathPoints(3, :) - pathPoints(1, :));
    [outerLaneSide(index), outerLaneCoordinate(index), ~, ...
        outerLaneEnvelopeClearance(index)] = ...
        outerLaneDescriptor(transitionGeometry, stateGeometry, ...
        index, rules);
end

inventory = table( ...
    uint32(transitionGeometry.SSId), ...
    transitionGeometry.Display, ...
    transitionGeometry.ParentDisplay, ...
    isDefault, isSelfLoop, geometryComplete, ...
    transitionGeometry.SourceOClock, ...
    transitionGeometry.DestinationOClock, ...
    transitionGeometry.SourceEndpoint(:, 1), ...
    transitionGeometry.SourceEndpoint(:, 2), ...
    transitionGeometry.MidPoint(:, 1), ...
    transitionGeometry.MidPoint(:, 2), ...
    transitionGeometry.DestinationEndpoint(:, 1), ...
    transitionGeometry.DestinationEndpoint(:, 2), ...
    pathLength, directLength, outerLaneSide, outerLaneCoordinate, ...
    outerLaneEnvelopeClearance, ...
    VariableNames=[ ...
    "SSId", "Transition", "Scope", "IsDefault", "IsSelfLoop", ...
    "GeometryComplete", "SourceOClock", "DestinationOClock", ...
    "SourceX", "SourceY", "MidPointX", "MidPointY", ...
    "DestinationX", "DestinationY", "PathLengthPixels", ...
    "DirectLengthPixels", "OuterLaneSide", "OuterLaneCoordinate", ...
    "OuterLaneEnvelopeClearancePixels"]);
end

function violations = inspectRoutingCompleteness( ...
        transitions, transitionGeometry)
transitionCount = numel(transitions);
collector = createCollector(transitionCount);
for index = 1:transitionCount
    destinationPresent = ~isempty(transitions(index).Destination);
    geometryComplete = routingGeometryIsComplete( ...
        transitionGeometry, index);
    if ~destinationPresent || ~geometryComplete
        collector = appendViolation(collector, ...
            "RoutingCompleteness", ...
            transitionGeometry.ParentDisplay(index), ...
            transitionGeometry.Display(index), "", ...
            double(destinationPresent && geometryComplete), 1, ...
            routingCompletenessDetail( ...
            transitionGeometry, index, destinationPresent));
    end
end
violations = finishCollector(collector);
end

function violations = inspectCompletePathOverlaps( ...
        transitionGeometry, rules)
transitionCount = numel(transitionGeometry.Key);
collector = createCollector( ...
    transitionCount * max(transitionCount - 1, 0) / 2);
for firstIndex = 1:transitionCount
    firstPath = transitionPathPoints(transitionGeometry, firstIndex);
    firstLength = approximatePathLength(firstPath);
    if firstLength <= rules.GeometryTolerancePixels
        continue
    end
    firstSamples = resamplePolyline( ...
        firstPath, rules.RoutingSampleCount);
    for secondIndex = firstIndex + 1:transitionCount
        if transitionGeometry.ParentKey(firstIndex) ~= ...
                transitionGeometry.ParentKey(secondIndex)
            continue
        end
        secondPath = transitionPathPoints( ...
            transitionGeometry, secondIndex);
        secondLength = approximatePathLength(secondPath);
        if secondLength <= rules.GeometryTolerancePixels
            continue
        end
        relativeLengthDifference = abs(firstLength - secondLength) / ...
            max(firstLength, secondLength);
        if relativeLengthDifference > ...
                rules.CompletePathLengthRatioTolerance
            continue
        end
        secondSamples = resamplePolyline( ...
            secondPath, rules.RoutingSampleCount);
        forwardDistance = max(vecnorm( ...
            firstSamples - secondSamples, 2, 2));
        reverseDistance = max(vecnorm( ...
            firstSamples - flipud(secondSamples), 2, 2));
        pathDistance = min(forwardDistance, reverseDistance);
        if pathDistance <= rules.CompletePathOverlapTolerancePixels
            collector = appendViolation(collector, ...
                "CompletePathOverlap", ...
                transitionGeometry.ParentDisplay(firstIndex), ...
                transitionGeometry.Display(firstIndex), ...
                transitionGeometry.Display(secondIndex), ...
                pathDistance, ...
                rules.CompletePathOverlapTolerancePixels, ...
                sprintf([ ...
                'Complete sampled paths are within %.1f pixels. ' ...
                'First path %s; second path %s.'], ...
                pathDistance, mat2str(firstPath, 5), ...
                mat2str(secondPath, 5)));
        end
    end
end
violations = finishCollector(collector);
end

function violations = inspectMidPointStateIntersections( ...
        transitionGeometry, stateGeometry, rules)
transitionCount = numel(transitionGeometry.Key);
stateCount = numel(stateGeometry.Key);
collector = createCollector(transitionCount * stateCount);
for transitionIndex = 1:transitionCount
    midPoint = transitionGeometry.MidPoint(transitionIndex, :);
    for stateIndex = 1:stateCount
        if transitionGeometry.ParentKey(transitionIndex) ~= ...
                stateGeometry.ParentKey(stateIndex)
            continue
        end
        if pointInsideRectangle(midPoint, ...
                stateGeometry.Position(stateIndex, :), ...
                rules.GeometryTolerancePixels)
            relation = labelStateRelation(transitionGeometry, ...
                transitionIndex, stateGeometry.Key(stateIndex));
            collector = appendViolation(collector, ...
                "MidPointInsideState", ...
                transitionGeometry.ParentDisplay(transitionIndex), ...
                transitionGeometry.Display(transitionIndex), ...
                stateGeometry.Display(stateIndex), 1, 0, ...
                sprintf( ...
                'Relation=%s; midpoint %s is inside state rectangle %s.', ...
                relation, mat2str(midPoint, 5), ...
                mat2str(stateGeometry.Position(stateIndex, :), 5)));
        end
    end
end
violations = finishCollector(collector);
end

function violations = inspectSelfLoopOClockSeparation( ...
        transitions, transitionGeometry, rules)
transitionCount = numel(transitions);
collector = createCollector(transitionCount);
for index = 1:transitionCount
    isStateSelfLoop = ~isempty(transitions(index).Source) && ...
        isa(transitions(index).Source, "Stateflow.State") && ...
        transitionGeometry.SourceKey(index) == ...
        transitionGeometry.DestinationKey(index);
    if ~isStateSelfLoop
        continue
    end
    separation = circularClockSeparation( ...
        transitionGeometry.SourceOClock(index), ...
        transitionGeometry.DestinationOClock(index));
    if separation < rules.MinimumSelfLoopOClockSeparationHours
        collector = appendViolation(collector, ...
            "SelfLoopOClockSeparation", ...
            transitionGeometry.ParentDisplay(index), ...
            transitionGeometry.Display(index), ...
            objectDisplay(transitions(index).Source), separation, ...
            rules.MinimumSelfLoopOClockSeparationHours, ...
            sprintf([ ...
            'SourceOClock %.2f and DestinationOClock %.2f are ' ...
            'separated by %.2f clock hours.'], ...
            transitionGeometry.SourceOClock(index), ...
            transitionGeometry.DestinationOClock(index), separation));
    end
end
violations = finishCollector(collector);
end

function violations = inspectOuterLaneSpacing( ...
        transitionGeometry, stateGeometry, rules)
transitionCount = numel(transitionGeometry.Key);
laneSide = strings(transitionCount, 1);
laneCoordinate = nan(transitionCount, 1);
laneSpan = nan(transitionCount, 2);
for index = 1:transitionCount
    [laneSide(index), laneCoordinate(index), laneSpan(index, :)] = ...
        outerLaneDescriptor(transitionGeometry, stateGeometry, ...
        index, rules);
end

collector = createCollector( ...
    transitionCount * max(transitionCount - 1, 0) / 2);
for firstIndex = 1:transitionCount
    if strlength(laneSide(firstIndex)) == 0
        continue
    end
    for secondIndex = firstIndex + 1:transitionCount
        sameLaneFamily = ...
            transitionGeometry.ParentKey(firstIndex) == ...
            transitionGeometry.ParentKey(secondIndex) && ...
            laneSide(firstIndex) == laneSide(secondIndex);
        if ~sameLaneFamily
            continue
        end
        spanOverlap = min( ...
            laneSpan(firstIndex, 2), laneSpan(secondIndex, 2)) - ...
            max(laneSpan(firstIndex, 1), laneSpan(secondIndex, 1));
        laneGap = abs( ...
            laneCoordinate(firstIndex) - laneCoordinate(secondIndex));
        if spanOverlap > rules.GeometryTolerancePixels && ...
                laneGap + rules.GeometryTolerancePixels < ...
                rules.MinimumOuterLaneGapPixels
            collector = appendViolation(collector, ...
                "OuterLaneSpacing", ...
                transitionGeometry.ParentDisplay(firstIndex), ...
                transitionGeometry.Display(firstIndex), ...
                transitionGeometry.Display(secondIndex), laneGap, ...
                rules.MinimumOuterLaneGapPixels, ...
                sprintf([ ...
                '%s outer lanes at %.1f and %.1f pixels overlap ' ...
                'along their travel span.'], ...
                laneSide(firstIndex), laneCoordinate(firstIndex), ...
                laneCoordinate(secondIndex)));
        end
    end
end
violations = finishCollector(collector);
end

function violations = inspectOuterLaneEnvelopeClearance( ...
        transitionGeometry, stateGeometry, rules)
transitionCount = numel(transitionGeometry.Key);
collector = createCollector(transitionCount);
for index = 1:transitionCount
    [laneSide, laneCoordinate, ~, clearance, envelope] = ...
        outerLaneDescriptor(transitionGeometry, stateGeometry, ...
        index, rules);
    if strlength(laneSide) == 0
        continue
    end
    if clearance + rules.GeometryTolerancePixels < ...
            rules.MinimumOuterLaneEnvelopeClearancePixels
        collector = appendViolation(collector, ...
            "OuterLaneEnvelopeClearance", ...
            transitionGeometry.ParentDisplay(index), ...
            transitionGeometry.Display(index), "", clearance, ...
            rules.MinimumOuterLaneEnvelopeClearancePixels, ...
            sprintf([ ...
            '%s outer-lane coordinate %.1f has %.1f pixels of ' ...
            'clearance from sibling-state envelope ' ...
            '[left top right bottom] %s.'], ...
            laneSide, laneCoordinate, clearance, ...
            mat2str(envelope, 5)));
    end
end
violations = finishCollector(collector);
end

function violations = inspectExcessiveOuterLaneClearance( ...
        transitionGeometry, stateGeometry, rules)
transitionCount = numel(transitionGeometry.Key);
collector = createCollector(transitionCount);
for index = 1:transitionCount
    [laneSide, laneCoordinate, ~, clearance, envelope] = ...
        outerLaneDescriptor(transitionGeometry, stateGeometry, ...
        index, rules);
    if strlength(laneSide) == 0 || ...
            clearance <= ...
            rules.MaximumOuterLaneEnvelopeClearancePixels + ...
            rules.GeometryTolerancePixels
        continue
    end
    collector = appendViolation(collector, ...
        "ExcessiveOuterLaneClearance", ...
        transitionGeometry.SubviewerDisplay(index), ...
        transitionGeometry.Display(index), "", clearance, ...
        rules.MaximumOuterLaneEnvelopeClearancePixels, ...
        sprintf([ ...
        '%s outer-lane coordinate %.1f is %.1f pixels from the ' ...
        'state envelope %s and expands the chart canvas excessively.'], ...
        laneSide, laneCoordinate, clearance, mat2str(envelope, 5)));
end
violations = finishCollector(collector);
end

function inventory = buildScopeCanvasInventory( ...
        transitionGeometry, stateGeometry)
scopeKeys = unique(stateGeometry.SubviewerKey, "stable");
scopeCount = numel(scopeKeys);
scope = strings(scopeCount, 1);
stateCount = zeros(scopeCount, 1);
stateWidth = zeros(scopeCount, 1);
stateHeight = zeros(scopeCount, 1);
graphicWidth = zeros(scopeCount, 1);
graphicHeight = zeros(scopeCount, 1);
stateBBoxUtilization = zeros(scopeCount, 1);
leftExpansion = zeros(scopeCount, 1);
rightExpansion = zeros(scopeCount, 1);
topExpansion = zeros(scopeCount, 1);
bottomExpansion = zeros(scopeCount, 1);

for scopeIndex = 1:scopeCount
    stateMask = stateGeometry.SubviewerKey == scopeKeys(scopeIndex);
    transitionMask = ...
        transitionGeometry.SubviewerKey == scopeKeys(scopeIndex);
    positions = stateGeometry.Position(stateMask, :);
    scope(scopeIndex) = stateGeometry.SubviewerDisplay( ...
        find(stateMask, 1, "first"));
    stateCount(scopeIndex) = nnz(stateMask);

    stateBounds = [ ...
        min(positions(:, 1)), min(positions(:, 2)), ...
        max(positions(:, 1) + positions(:, 3)), ...
        max(positions(:, 2) + positions(:, 4))];
    pathX = [ ...
        transitionGeometry.SourceEndpoint(transitionMask, 1)
        transitionGeometry.MidPoint(transitionMask, 1)
        transitionGeometry.DestinationEndpoint(transitionMask, 1)];
    pathY = [ ...
        transitionGeometry.SourceEndpoint(transitionMask, 2)
        transitionGeometry.MidPoint(transitionMask, 2)
        transitionGeometry.DestinationEndpoint(transitionMask, 2)];
    labelPositions = ...
        transitionGeometry.LabelPosition(transitionMask, :);
    graphicBounds = [ ...
        min([stateBounds(1); pathX; labelPositions(:, 1)]), ...
        min([stateBounds(2); pathY; labelPositions(:, 2)]), ...
        max([stateBounds(3); pathX; ...
        labelPositions(:, 1) + labelPositions(:, 3)]), ...
        max([stateBounds(4); pathY; ...
        labelPositions(:, 2) + labelPositions(:, 4)])];

    stateWidth(scopeIndex) = stateBounds(3) - stateBounds(1);
    stateHeight(scopeIndex) = stateBounds(4) - stateBounds(2);
    graphicWidth(scopeIndex) = graphicBounds(3) - graphicBounds(1);
    graphicHeight(scopeIndex) = graphicBounds(4) - graphicBounds(2);
    stateBBoxUtilization(scopeIndex) = ...
        stateWidth(scopeIndex) * stateHeight(scopeIndex) / ...
        (graphicWidth(scopeIndex) * graphicHeight(scopeIndex));
    leftExpansion(scopeIndex) = stateBounds(1) - graphicBounds(1);
    rightExpansion(scopeIndex) = graphicBounds(3) - stateBounds(3);
    topExpansion(scopeIndex) = stateBounds(2) - graphicBounds(2);
    bottomExpansion(scopeIndex) = graphicBounds(4) - stateBounds(4);
end

inventory = table( ...
    scopeKeys, scope, stateCount, stateWidth, stateHeight, ...
    graphicWidth, graphicHeight, stateBBoxUtilization, ...
    leftExpansion, rightExpansion, topExpansion, bottomExpansion, ...
    VariableNames=[ ...
    "ScopeKey", "Scope", "StateCount", "StateWidth", "StateHeight", ...
    "GraphicWidth", "GraphicHeight", "StateBBoxUtilization", ...
    "LeftExpansion", "RightExpansion", "TopExpansion", ...
    "BottomExpansion"]);
end

function violations = inspectScopeCanvasBalance(inventory, rules)
collector = createCollector(2 * height(inventory));
for index = 1:height(inventory)
    if inventory.StateBBoxUtilization(index) + eps < ...
            rules.MinimumScopeStateBBoxUtilization
        collector = appendViolation(collector, ...
            "ScopeStateBBoxUtilization", inventory.Scope(index), ...
            "State bounding box", "Graphical bounding box", ...
            inventory.StateBBoxUtilization(index), ...
            rules.MinimumScopeStateBBoxUtilization, ...
            sprintf([ ...
            'State bbox %.1f x %.1f; graphical bbox %.1f x %.1f; ' ...
            'utilization %.3f.'], ...
            inventory.StateWidth(index), inventory.StateHeight(index), ...
            inventory.GraphicWidth(index), ...
            inventory.GraphicHeight(index), ...
            inventory.StateBBoxUtilization(index)));
    end
    expansions = [ ...
        inventory.LeftExpansion(index), ...
        inventory.RightExpansion(index), ...
        inventory.TopExpansion(index), ...
        inventory.BottomExpansion(index)];
    maximumExpansion = max(expansions);
    if maximumExpansion > ...
            rules.MaximumScopeCanvasExpansionPixels + ...
            rules.GeometryTolerancePixels
        collector = appendViolation(collector, ...
            "ScopeCanvasExpansion", inventory.Scope(index), ...
            "State bounding box", "Graphical bounding box", ...
            maximumExpansion, ...
            rules.MaximumScopeCanvasExpansionPixels, ...
            sprintf( ...
            'Canvas expansion [left right top bottom] is %s pixels.', ...
            mat2str(expansions, 5)));
    end
end
violations = finishCollector(collector);
end

function violations = inspectBidirectionalOuterDetours( ...
        transitionGeometry, stateGeometry, rules)
transitionCount = numel(transitionGeometry.Key);
collector = createCollector(2 * transitionCount);
for index = 1:transitionCount
    if ~hasReciprocalTransition(transitionGeometry, index)
        continue
    end
    [laneSide, ~, ~, clearance, ~] = outerLaneDescriptor( ...
        transitionGeometry, stateGeometry, index, rules);
    if strlength(laneSide) > 0 && ...
            clearance > ...
            rules.MaximumBidirectionalEnvelopeExcursionPixels + ...
            rules.GeometryTolerancePixels
        collector = appendViolation(collector, ...
            "BidirectionalOuterExcursion", ...
            transitionGeometry.SubviewerDisplay(index), ...
            transitionGeometry.Display(index), "", clearance, ...
            rules.MaximumBidirectionalEnvelopeExcursionPixels, ...
            sprintf( ...
            'Reciprocal path uses a %s excursion of %.1f pixels.', ...
            laneSide, clearance));
    end
    pathPoints = transitionPathPoints(transitionGeometry, index);
    directLength = norm(pathPoints(3, :) - pathPoints(1, :));
    if directLength <= rules.GeometryTolerancePixels
        continue
    end
    detourRatio = approximatePathLength(pathPoints) / directLength;
    if detourRatio > rules.MaximumBidirectionalDetourRatio
        collector = appendViolation(collector, ...
            "BidirectionalDetourRatio", ...
            transitionGeometry.SubviewerDisplay(index), ...
            transitionGeometry.Display(index), "", detourRatio, ...
            rules.MaximumBidirectionalDetourRatio, ...
            sprintf( ...
            'Reciprocal path/direct length ratio is %.3f for path %s.', ...
            detourRatio, mat2str(pathPoints, 5)));
    end
end
violations = finishCollector(collector);
end

function violations = inspectShortTransitionStraightness( ...
        transitions, transitionGeometry, stateGeometry, rules)
transitionCount = numel(transitions);
collector = createCollector(transitionCount);
for index = 1:transitionCount
    sourceMatches = find( ...
        stateGeometry.Key == transitionGeometry.SourceKey(index));
    destinationMatches = find( ...
        stateGeometry.Key == transitionGeometry.DestinationKey(index));
    if ~isscalar(sourceMatches) || ~isscalar(destinationMatches) || ...
            sourceMatches == destinationMatches || ...
            hasReciprocalTransition(transitionGeometry, index) || ...
            hasParallelTransition(transitionGeometry, index)
        continue
    end
    sourceRectangle = stateGeometry.Position(sourceMatches, :);
    destinationRectangle = stateGeometry.Position(destinationMatches, :);
    stateGap = rectangleDistance( ...
        sourceRectangle, destinationRectangle);
    pathPoints = transitionPathPoints(transitionGeometry, index);
    directLength = norm(pathPoints(3, :) - pathPoints(1, :));
    if stateGap > rules.ShortAdjacentStateGapPixels || ...
            directLength > rules.ShortTransitionMaximumLengthPixels || ...
            directLength <= rules.GeometryTolerancePixels
        continue
    end
    deviation = pointToSegmentDistance( ...
        pathPoints(2, :), pathPoints(1, :), pathPoints(3, :));
    lengthRatio = approximatePathLength(pathPoints) / directLength;
    if deviation > rules.ShortTransitionMaximumDeviationPixels || ...
            lengthRatio > rules.ShortTransitionMaximumLengthRatio
        collector = appendViolation(collector, ...
            "ShortTransitionStraightness", ...
            transitionGeometry.ParentDisplay(index), ...
            transitionGeometry.Display(index), "", deviation, ...
            rules.ShortTransitionMaximumDeviationPixels, ...
            sprintf([ ...
            'Adjacent-state gap %.1f; midpoint deviation %.1f; ' ...
            'path/direct length ratio %.3f; path %s.'], ...
            stateGap, deviation, lengthRatio, ...
            mat2str(pathPoints, 5)));
    end
end
violations = finishCollector(collector);
end

function violations = inspectBidirectionalTransitionSeparation( ...
        transitionGeometry, rules)
transitionCount = numel(transitionGeometry.Key);
collector = createCollector( ...
    transitionCount * max(transitionCount - 1, 0) / 2);
sampleCount = rules.RoutingSampleCount;
firstInteriorIndex = max(2, ceil(0.2 * sampleCount));
lastInteriorIndex = min(sampleCount - 1, floor(0.8 * sampleCount));
interiorIndices = firstInteriorIndex:lastInteriorIndex;

for firstIndex = 1:transitionCount
    if transitionGeometry.SourceKey(firstIndex) == "<none>"
        continue
    end
    for secondIndex = firstIndex + 1:transitionCount
        isReversePair = ...
            transitionGeometry.ParentKey(firstIndex) == ...
            transitionGeometry.ParentKey(secondIndex) && ...
            transitionGeometry.SourceKey(firstIndex) == ...
            transitionGeometry.DestinationKey(secondIndex) && ...
            transitionGeometry.DestinationKey(firstIndex) == ...
            transitionGeometry.SourceKey(secondIndex);
        if ~isReversePair
            continue
        end
        firstPath = transitionPathPoints( ...
            transitionGeometry, firstIndex);
        secondPath = transitionPathPoints( ...
            transitionGeometry, secondIndex);
        firstSamples = resamplePolyline(firstPath, sampleCount);
        secondSamples = resamplePolyline(secondPath, sampleCount);
        firstInterior = firstSamples(interiorIndices, :);
        secondInterior = secondSamples(interiorIndices, :);
        horizontalDistances = firstInterior(:, 1) - ...
            secondInterior(:, 1).';
        verticalDistances = firstInterior(:, 2) - ...
            secondInterior(:, 2).';
        minimumSeparation = min( ...
            hypot(horizontalDistances, verticalDistances), [], "all");
        if minimumSeparation < ...
                rules.MinimumBidirectionalSeparationPixels
            collector = appendViolation(collector, ...
                "BidirectionalSeparation", ...
                transitionGeometry.ParentDisplay(firstIndex), ...
                transitionGeometry.Display(firstIndex), ...
                transitionGeometry.Display(secondIndex), ...
                minimumSeparation, ...
                rules.MinimumBidirectionalSeparationPixels, ...
                sprintf([ ...
                'Interior sampled paths approach within %.1f pixels. ' ...
                'First path %s; reverse path %s.'], ...
                minimumSeparation, mat2str(firstPath, 5), ...
                mat2str(secondPath, 5)));
        end
    end
end
violations = finishCollector(collector);
end

function violations = inspectApproximatePathShapes( ...
        transitionGeometry, stateGeometry, rules)
transitionCount = numel(transitionGeometry.Key);
collector = createCollector(transitionCount);
for index = 1:transitionCount
    pathPoints = transitionPathPoints(transitionGeometry, index);
    isSelfLoop = transitionGeometry.SourceKey(index) ~= "<none>" && ...
        transitionGeometry.SourceKey(index) == ...
        transitionGeometry.DestinationKey(index);
    if isSelfLoop
        pathSpan = max(max(pathPoints, [], 1) - ...
            min(pathPoints, [], 1));
        if pathSpan < rules.MinimumSelfLoopSpanPixels
            collector = appendViolation(collector, ...
                "SmallSelfLoopApproximation", ...
                transitionGeometry.ParentDisplay(index), ...
                transitionGeometry.Display(index), "", pathSpan, ...
                rules.MinimumSelfLoopSpanPixels, ...
                sprintf("Self-loop path span is %.1f pixels: %s.", ...
                pathSpan, mat2str(pathPoints, 5)));
        end
        continue
    end

    [outerLaneSide, ~] = outerLaneDescriptor( ...
        transitionGeometry, stateGeometry, index, rules);
    directVector = pathPoints(3, :) - pathPoints(1, :);
    directLength = norm(directVector);
    firstVector = pathPoints(2, :) - pathPoints(1, :);
    secondVector = pathPoints(3, :) - pathPoints(2, :);
    segmentNormProduct = norm(firstVector) * norm(secondVector);
    if directLength <= rules.GeometryTolerancePixels || ...
            directLength > rules.ShortTransitionMaximumLengthPixels || ...
            strlength(outerLaneSide) > 0 || ...
            segmentNormProduct <= eps
        continue
    end
    detourRatio = approximatePathLength(pathPoints) / directLength;
    turnCosine = dot(firstVector, secondVector) / segmentNormProduct;
    if detourRatio > rules.MaximumShortPathDetourRatio || ...
            turnCosine < rules.BacktrackingCosineThreshold
        collector = appendViolation(collector, ...
            "SmallLoopOrSShapeApproximation", ...
            transitionGeometry.ParentDisplay(index), ...
            transitionGeometry.Display(index), "", detourRatio, ...
            rules.MaximumShortPathDetourRatio, ...
            sprintf([ ...
            'Two-segment approximation has detour ratio %.3f and ' ...
            'turn cosine %.3f for path %s.'], ...
            detourRatio, turnCosine, mat2str(pathPoints, 5)));
    end
end
violations = finishCollector(collector);
end

function violations = inspectLabelPathOverlaps( ...
        transitionGeometry, rules)
transitionCount = numel(transitionGeometry.Key);
collector = createCollector(transitionCount * max(transitionCount - 1, 0));
for labelIndex = 1:transitionCount
    if strlength(strtrim(transitionGeometry.Label(labelIndex))) == 0
        continue
    end
    labelRectangle = insetRectangle( ...
        transitionGeometry.LabelPosition(labelIndex, :), ...
        rules.LabelPathInsetPixels);
    if labelRectangle(3) <= 0 || labelRectangle(4) <= 0
        continue
    end
    for pathIndex = 1:transitionCount
        if labelIndex == pathIndex || ...
                transitionGeometry.ParentKey(labelIndex) ~= ...
                transitionGeometry.ParentKey(pathIndex)
            continue
        end
        pathPoints = transitionPathPoints( ...
            transitionGeometry, pathIndex);
        overlapsPath = segmentIntersectsRectangle( ...
            pathPoints(1, :), pathPoints(2, :), labelRectangle) || ...
            segmentIntersectsRectangle( ...
            pathPoints(2, :), pathPoints(3, :), labelRectangle);
        if overlapsPath
            collector = appendViolation(collector, ...
                "LabelPathOverlap", ...
                transitionGeometry.ParentDisplay(labelIndex), ...
                transitionGeometry.Display(labelIndex), ...
                transitionGeometry.Display(pathIndex), 1, 0, ...
                sprintf([ ...
                'Inset label rectangle %s intersects another ' ...
                'transition two-segment path %s.'], ...
                mat2str(labelRectangle, 5), ...
                mat2str(pathPoints, 5)));
        end
    end
end
violations = finishCollector(collector);
end

function violations = inspectPathPathInteractions( ...
        transitionGeometry, rules)
transitionCount = numel(transitionGeometry.Key);
collector = createCollector( ...
    transitionCount * max(transitionCount - 1, 0) / 2);
for firstIndex = 1:transitionCount
    firstPath = transitionPathPoints(transitionGeometry, firstIndex);
    for secondIndex = firstIndex + 1:transitionCount
        if transitionGeometry.ParentKey(firstIndex) ~= ...
                transitionGeometry.ParentKey(secondIndex)
            continue
        end
        secondPath = transitionPathPoints( ...
            transitionGeometry, secondIndex);
        [interacts, interactionKind, interactionPoint, measurement] = ...
            polylineInteraction(firstPath, secondPath, rules);
        if interacts
            collector = appendViolation(collector, ...
                "PathPathCrossingOrPartialOverlap", ...
                transitionGeometry.ParentDisplay(firstIndex), ...
                transitionGeometry.Display(firstIndex), ...
                transitionGeometry.Display(secondIndex), ...
                measurement, 0, ...
                sprintf( ...
                '%s near %s. First path %s; second path %s.', ...
                interactionKind, mat2str(interactionPoint, 5), ...
                mat2str(firstPath, 5), mat2str(secondPath, 5)));
        end
    end
end
violations = finishCollector(collector);
end

function [overlapWidth, overlapHeight] = rectangleOverlap(first, second)
firstRight = first(1) + first(3);
firstBottom = first(2) + first(4);
secondRight = second(1) + second(3);
secondBottom = second(2) + second(4);
overlapWidth = min(firstRight, secondRight) - ...
    max(first(1), second(1));
overlapHeight = min(firstBottom, secondBottom) - ...
    max(first(2), second(2));
end

function relation = labelStateRelation( ...
        transitionGeometry, transitionIndex, stateKey)
if stateKey == transitionGeometry.SourceKey(transitionIndex)
    relation = "source";
elseif stateKey == transitionGeometry.DestinationKey(transitionIndex)
    relation = "destination";
else
    relation = "unrelated";
end
end

function rectangle = insetRectangle(rectangle, inset)
rectangle = [
    rectangle(1) + inset
    rectangle(2) + inset
    max(rectangle(3) - 2 * inset, 0)
    max(rectangle(4) - 2 * inset, 0)
    ].';
end

function intersects = segmentIntersectsRectangle( ...
        startPoint, endPoint, rectangle)
if rectangle(3) <= 0 || rectangle(4) <= 0
    intersects = false;
    return
end

minimumX = rectangle(1);
maximumX = rectangle(1) + rectangle(3);
minimumY = rectangle(2);
maximumY = rectangle(2) + rectangle(4);
delta = endPoint - startPoint;
p = [-delta(1), delta(1), -delta(2), delta(2)];
q = [
    startPoint(1) - minimumX
    maximumX - startPoint(1)
    startPoint(2) - minimumY
    maximumY - startPoint(2)
    ].';
lowerParameter = 0;
upperParameter = 1;

for index = 1:4
    if abs(p(index)) < eps
        if q(index) < 0
            intersects = false;
            return
        end
        continue
    end
    candidate = q(index) / p(index);
    if p(index) < 0
        lowerParameter = max(lowerParameter, candidate);
    else
        upperParameter = min(upperParameter, candidate);
    end
    if lowerParameter > upperParameter
        intersects = false;
        return
    end
end
intersects = true;
end

function [interacts, interactionKind, interactionPoint, measurement] = ...
        polylineInteraction(firstPath, secondPath, rules)
interacts = false;
interactionKind = "";
interactionPoint = [NaN, NaN];
measurement = NaN;
for firstSegment = 1:2
    for secondSegment = 1:2
        [segmentInteracts, segmentKind, segmentPoint, ...
            segmentMeasurement] = segmentInteraction( ...
            firstPath(firstSegment, :), ...
            firstPath(firstSegment + 1, :), ...
            secondPath(secondSegment, :), ...
            secondPath(secondSegment + 1, :), rules);
        if ~segmentInteracts
            continue
        end
        nearPathEndpoint = pointNearPathEndpoint( ...
            segmentPoint, firstPath, secondPath, ...
            rules.PathInteractionEndpointAllowancePixels);
        if nearPathEndpoint && ...
                segmentKind ~= "partial collinear overlap"
            continue
        end
        if nearPathEndpoint && ...
                segmentMeasurement <= ...
                2 * rules.PathInteractionEndpointAllowancePixels
            continue
        end
        interacts = true;
        interactionKind = segmentKind;
        interactionPoint = segmentPoint;
        measurement = segmentMeasurement;
        return
    end
end
end

function [interacts, interactionKind, interactionPoint, measurement] = ...
        segmentInteraction(firstStart, firstEnd, ...
        secondStart, secondEnd, rules)
interacts = false;
interactionKind = "";
interactionPoint = [NaN, NaN];
measurement = NaN;
firstVector = firstEnd - firstStart;
secondVector = secondEnd - secondStart;
firstLength = norm(firstVector);
secondLength = norm(secondVector);
if firstLength <= eps || secondLength <= eps
    return
end

vectorCross = cross2d(firstVector, secondVector);
relativeStart = secondStart - firstStart;
parallelMeasure = abs(vectorCross) / (firstLength * secondLength);
if parallelMeasure <= 1e-8
    lineDistance = abs(cross2d(relativeStart, firstVector)) / ...
        firstLength;
    if lineDistance > rules.GeometryTolerancePixels
        return
    end
    firstDirection = firstVector / firstLength;
    secondParameters = [
        dot(secondStart - firstStart, firstDirection)
        dot(secondEnd - firstStart, firstDirection)
        ];
    overlapStart = max(0, min(secondParameters));
    overlapEnd = min(firstLength, max(secondParameters));
    overlapLength = overlapEnd - overlapStart;
    if overlapLength < rules.MinimumPartialPathOverlapPixels
        return
    end
    interacts = true;
    interactionKind = "partial collinear overlap";
    interactionPoint = firstStart + ...
        0.5 * (overlapStart + overlapEnd) * firstDirection;
    measurement = overlapLength;
    return
end

firstParameter = cross2d(relativeStart, secondVector) / vectorCross;
secondParameter = cross2d(relativeStart, firstVector) / vectorCross;
parameterTolerance = 1e-9;
if firstParameter < -parameterTolerance || ...
        firstParameter > 1 + parameterTolerance || ...
        secondParameter < -parameterTolerance || ...
        secondParameter > 1 + parameterTolerance
    return
end
interacts = true;
interactionKind = "segment crossing";
interactionPoint = firstStart + firstParameter * firstVector;
measurement = 1;
end

function nearEndpoint = pointNearPathEndpoint( ...
        point, firstPath, secondPath, allowance)
pathEndpoints = [
    firstPath(1, :)
    firstPath(3, :)
    secondPath(1, :)
    secondPath(3, :)
    ];
nearEndpoint = any(vecnorm(pathEndpoints - point, 2, 2) <= allowance);
end

function result = cross2d(firstVector, secondVector)
result = firstVector(1) * secondVector(2) - ...
    firstVector(2) * secondVector(1);
end

function pathPoints = transitionPathPoints(transitionGeometry, index)
pathPoints = [
    transitionGeometry.SourceEndpoint(index, :)
    transitionGeometry.MidPoint(index, :)
    transitionGeometry.DestinationEndpoint(index, :)
    ];
end

function complete = routingGeometryIsComplete(transitionGeometry, index)
pathPoints = transitionPathPoints(transitionGeometry, index);
labelPosition = transitionGeometry.LabelPosition(index, :);
sourceOClock = transitionGeometry.SourceOClock(index);
destinationOClock = transitionGeometry.DestinationOClock(index);
complete = all(isfinite(pathPoints), "all") && ...
    all(isfinite(labelPosition)) && ...
    labelPosition(3) >= 0 && labelPosition(4) >= 0 && ...
    isfinite(sourceOClock) && sourceOClock >= 0 && ...
    sourceOClock <= 12 && ...
    isfinite(destinationOClock) && destinationOClock >= 0 && ...
    destinationOClock <= 12 && ...
    approximatePathLength(pathPoints) > eps;
end

function detail = routingCompletenessDetail( ...
        transitionGeometry, index, destinationPresent)
parts = strings(5, 1);
partCount = 0;
pathPoints = transitionPathPoints(transitionGeometry, index);
labelPosition = transitionGeometry.LabelPosition(index, :);
sourceOClock = transitionGeometry.SourceOClock(index);
destinationOClock = transitionGeometry.DestinationOClock(index);

if ~destinationPresent
    partCount = partCount + 1;
    parts(partCount) = "destination is missing";
end
if any(~isfinite(pathPoints), "all") || ...
        approximatePathLength(pathPoints) <= eps
    partCount = partCount + 1;
    parts(partCount) = "path endpoints or midpoint are invalid";
end
if any(~isfinite(labelPosition)) || ...
        labelPosition(3) < 0 || labelPosition(4) < 0
    partCount = partCount + 1;
    parts(partCount) = "LabelPosition is invalid";
end
if ~isfinite(sourceOClock) || sourceOClock < 0 || sourceOClock > 12
    partCount = partCount + 1;
    parts(partCount) = "SourceOClock is outside [0,12]";
end
if ~isfinite(destinationOClock) || ...
        destinationOClock < 0 || destinationOClock > 12
    partCount = partCount + 1;
    parts(partCount) = "DestinationOClock is outside [0,12]";
end
detail = join(parts(1:partCount), "; ");
end

function lengthPixels = approximatePathLength(pathPoints)
segmentVectors = diff(pathPoints, 1, 1);
lengthPixels = sum(vecnorm(segmentVectors, 2, 2));
end

function samples = resamplePolyline(pathPoints, sampleCount)
segmentLengths = vecnorm(diff(pathPoints, 1, 1), 2, 2);
totalLength = sum(segmentLengths);
samples = zeros(sampleCount, 2);
if totalLength <= eps
    samples(:, :) = pathPoints(1, :);
    return
end

targets = linspace(0, totalLength, sampleCount).';
firstSegmentEnd = segmentLengths(1);
for index = 1:sampleCount
    target = targets(index);
    if target <= firstSegmentEnd && segmentLengths(1) > eps
        fraction = target / segmentLengths(1);
        samples(index, :) = pathPoints(1, :) + ...
            fraction * (pathPoints(2, :) - pathPoints(1, :));
    elseif segmentLengths(2) > eps
        fraction = (target - firstSegmentEnd) / segmentLengths(2);
        fraction = min(max(fraction, 0), 1);
        samples(index, :) = pathPoints(2, :) + ...
            fraction * (pathPoints(3, :) - pathPoints(2, :));
    else
        samples(index, :) = pathPoints(2, :);
    end
end
end

function inside = pointInsideRectangle(point, rectangle, tolerance)
inside = point(1) > rectangle(1) + tolerance && ...
    point(1) < rectangle(1) + rectangle(3) - tolerance && ...
    point(2) > rectangle(2) + tolerance && ...
    point(2) < rectangle(2) + rectangle(4) - tolerance;
end

function separation = circularClockSeparation(firstClock, secondClock)
rawSeparation = mod(abs(firstClock - secondClock), 12);
separation = min(rawSeparation, 12 - rawSeparation);
end

function [side, coordinate, travelSpan, clearance, envelope] = ...
        outerLaneDescriptor( ...
        transitionGeometry, stateGeometry, transitionIndex, rules)
side = "";
coordinate = NaN;
travelSpan = [NaN, NaN];
clearance = NaN;
envelope = [NaN, NaN, NaN, NaN];
siblingMask = stateGeometry.ParentKey == ...
    transitionGeometry.ParentKey(transitionIndex);
if ~any(siblingMask)
    return
end

positions = stateGeometry.Position(siblingMask, :);
minimumX = min(positions(:, 1));
minimumY = min(positions(:, 2));
maximumX = max(positions(:, 1) + positions(:, 3));
maximumY = max(positions(:, 2) + positions(:, 4));
envelope = [minimumX, minimumY, maximumX, maximumY];
midPoint = transitionGeometry.MidPoint(transitionIndex, :);
outsideDistances = [
    minimumY - midPoint(2)
    midPoint(2) - maximumY
    minimumX - midPoint(1)
    midPoint(1) - maximumX
    ];
[maximumOutsideDistance, sideIndex] = max(outsideDistances);
if maximumOutsideDistance <= rules.OuterLaneDetectionMarginPixels
    return
end

sideNames = ["top", "bottom", "left", "right"];
side = sideNames(sideIndex);
clearance = maximumOutsideDistance;
pathPoints = transitionPathPoints(transitionGeometry, transitionIndex);
if side == "top" || side == "bottom"
    coordinate = midPoint(2);
    travelSpan = [min(pathPoints(:, 1)), max(pathPoints(:, 1))];
else
    coordinate = midPoint(1);
    travelSpan = [min(pathPoints(:, 2)), max(pathPoints(:, 2))];
end
end

function distance = rectangleDistance(firstRectangle, secondRectangle)
horizontalGap = max([ ...
    secondRectangle(1) - ...
    (firstRectangle(1) + firstRectangle(3)), ...
    firstRectangle(1) - ...
    (secondRectangle(1) + secondRectangle(3)), ...
    0]);
verticalGap = max([ ...
    secondRectangle(2) - ...
    (firstRectangle(2) + firstRectangle(4)), ...
    firstRectangle(2) - ...
    (secondRectangle(2) + secondRectangle(4)), ...
    0]);
distance = hypot(horizontalGap, verticalGap);
end

function distance = pointToSegmentDistance(point, startPoint, endPoint)
segment = endPoint - startPoint;
segmentLengthSquared = dot(segment, segment);
if segmentLengthSquared <= eps
    distance = norm(point - startPoint);
    return
end
projection = dot(point - startPoint, segment) / segmentLengthSquared;
projection = min(max(projection, 0), 1);
closestPoint = startPoint + projection * segment;
distance = norm(point - closestPoint);
end

function present = hasReciprocalTransition(transitionGeometry, index)
candidateMask = transitionGeometry.SourceKey == ...
    transitionGeometry.DestinationKey(index) & ...
    transitionGeometry.DestinationKey == ...
    transitionGeometry.SourceKey(index);
candidateMask(index) = false;
present = any(candidateMask);
end

function present = hasParallelTransition(transitionGeometry, index)
candidateMask = transitionGeometry.SourceKey == ...
    transitionGeometry.SourceKey(index) & ...
    transitionGeometry.DestinationKey == ...
    transitionGeometry.DestinationKey(index);
candidateMask(index) = false;
present = any(candidateMask);
end

function key = objectKey(object)
if isempty(object)
    key = "<none>";
elseif isa(object, "Stateflow.Chart")
    key = "Stateflow.Chart:" + string(object.Path);
elseif isprop(object, "SSIdNumber")
    key = string(class(object)) + ":" + ...
        string(double(object.SSIdNumber));
else
    key = string(class(object)) + ":" + objectDisplay(object);
end
end

function displayName = objectDisplay(object)
if isempty(object)
    displayName = "<none>";
elseif isa(object, "Stateflow.Chart")
    displayName = string(object.Path);
elseif isprop(object, "Name") && strlength(string(object.Name)) > 0
    displayName = string(object.Name);
    if isprop(object, "SSIdNumber")
        displayName = displayName + " [SSID " + ...
            string(double(object.SSIdNumber)) + "]";
    end
elseif isprop(object, "SSIdNumber")
    displayName = string(class(object)) + " [SSID " + ...
        string(double(object.SSIdNumber)) + "]";
else
    displayName = string(class(object));
end
end

function displayName = transitionDisplay(transition)
sourceName = objectDisplay(transition.Source);
destinationName = objectDisplay(transition.Destination);
label = replace(string(transition.LabelString), newline, " ");
label = strtrim(label);
if strlength(label) > 80
    label = extractBefore(label, 78) + "...";
end
displayName = "T" + string(double(transition.SSIdNumber)) + ...
    " " + sourceName + " -> " + destinationName;
if strlength(label) > 0
    displayName = displayName + " " + label;
end
end

function collector = createCollector(capacity)
capacity = max(1, ceil(capacity));
collector = struct;
collector.Count = 0;
collector.Category = strings(capacity, 1);
collector.Scope = strings(capacity, 1);
collector.ObjectA = strings(capacity, 1);
collector.ObjectB = strings(capacity, 1);
collector.Measurement = nan(capacity, 1);
collector.Required = nan(capacity, 1);
collector.Detail = strings(capacity, 1);
end

function collector = appendViolation(collector, category, scope, ...
        objectA, objectB, measurement, required, detail)
nextIndex = collector.Count + 1;
if nextIndex > numel(collector.Category)
    error("AMR:Stateflow:CollectorCapacityExceeded", ...
        "The graphical-layout violation collector capacity was exceeded.");
end
collector.Count = nextIndex;
collector.Category(nextIndex) = string(category);
collector.Scope(nextIndex) = string(scope);
collector.ObjectA(nextIndex) = string(objectA);
collector.ObjectB(nextIndex) = string(objectB);
collector.Measurement(nextIndex) = double(measurement);
collector.Required(nextIndex) = double(required);
collector.Detail(nextIndex) = string(detail);
end

function violations = finishCollector(collector)
indices = (1:collector.Count).';
violations = table( ...
    collector.Category(indices), ...
    collector.Scope(indices), ...
    collector.ObjectA(indices), ...
    collector.ObjectB(indices), ...
    collector.Measurement(indices), ...
    collector.Required(indices), ...
    collector.Detail(indices), ...
    VariableNames=[ ...
    "Category", "Scope", "ObjectA", "ObjectB", ...
    "Measurement", "Required", "Detail"]);
end

function diagnostic = formatDiagnostic(violations, emptyMessage)
if isempty(violations)
    diagnostic = string(emptyMessage);
else
    diagnostic = string(evalc("disp(violations)"));
end
end
