classdef StateflowGraphicalLayoutTest < matlab.unittest.TestCase
    %STATEFLOWGRAPHICALLAYOUTTEST Graphical quality gate for the supervisor.

    properties (SetAccess = private)
        LayoutReport
    end

    methods (TestClassSetup)
        function inspectSupervisorChart(testCase)
            projectRoot = fileparts(fileparts( ...
                fileparts(mfilename("fullpath"))));
            sourceFolder = fullfile(projectRoot, "src");
            modelFile = fullfile(projectRoot, "models", ...
                "prototypes", "amr_mission_supervisor.slx");
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture(sourceFolder));
            testCase.LayoutReport = ...
                amr.stateflow.inspectGraphicalLayout( ...
                modelFile, "MissionSupervisor");
        end
    end

    methods (Test)
        function hardGraphicalViolationsAreAbsent(testCase)
            testCase.verifyEqual( ...
                testCase.LayoutReport.HardViolationCount, uint32(0), ...
                testCase.LayoutReport.HardDiagnostic);
        end

        function stateTextFitAdvisoriesAreAbsent(testCase)
            testCase.verifyEqual( ...
                testCase.LayoutReport.AdvisoryCount, uint32(0), ...
                testCase.LayoutReport.AdvisoryDiagnostic);
        end

        function pathApproximationIsReported(testCase)
            testCase.verifyEqual( ...
                testCase.LayoutReport.PathApproximation, ...
                "SourceEndpoint-to-MidPoint-to-" + ...
                "DestinationEndpoint line segments");
        end

        function routingInventoryCoversEveryTransition(testCase)
            expectedCount = double( ...
                testCase.LayoutReport.TransitionCount);

            actualCount = height( ...
                testCase.LayoutReport.RoutingInventory);

            testCase.verifyEqual(actualCount, expectedCount);
        end

        function routingCompletenessViolationsAreAbsent(testCase)
            expectedCount = uint32(0);

            actualCount = testCase.LayoutReport. ...
                RoutingCompletenessViolationCount;

            testCase.verifyEqual(expectedCount, actualCount, ...
                testCase.LayoutReport.RoutingDiagnostic);
        end

        function exactRoutingGeometryChecksAreClear(testCase)
            expectedCounts = zeros(1, 6, "uint32");

            actualCounts = [
                testCase.LayoutReport. ...
                RoutingCompletenessViolationCount
                testCase.LayoutReport. ...
                MidPointStateIntersectionCount
                testCase.LayoutReport. ...
                SelfLoopOClockViolationCount
                testCase.LayoutReport. ...
                ExcessiveOuterLaneClearanceViolationCount
                testCase.LayoutReport. ...
                ScopeCanvasBalanceViolationCount
                testCase.LayoutReport. ...
                BidirectionalOuterDetourViolationCount
                ].';

            testCase.verifyEqual(actualCounts, expectedCounts, ...
                testCase.LayoutReport.RoutingDiagnostic);
        end

        function routingCountMatchesDiagnosticTables(testCase)
            expectedCount = uint32(sum([
                height(testCase.LayoutReport. ...
                RoutingCompletenessViolations)
                height(testCase.LayoutReport.CompletePathOverlaps)
                height(testCase.LayoutReport. ...
                MidPointStateIntersections)
                height(testCase.LayoutReport. ...
                SelfLoopOClockViolations)
                height(testCase.LayoutReport. ...
                OuterLaneSpacingViolations)
                height(testCase.LayoutReport. ...
                OuterLaneEnvelopeClearanceViolations)
                height(testCase.LayoutReport. ...
                ExcessiveOuterLaneClearanceViolations)
                height(testCase.LayoutReport. ...
                ScopeCanvasBalanceViolations)
                height(testCase.LayoutReport. ...
                BidirectionalOuterDetourViolations)
                height(testCase.LayoutReport. ...
                ShortTransitionStraightnessViolations)
                height(testCase.LayoutReport. ...
                BidirectionalTransitionViolations)
                height(testCase.LayoutReport.PathShapeViolations)
                height(testCase.LayoutReport.LabelPathOverlaps)
                height(testCase.LayoutReport. ...
                PathPathCrossingOrPartialOverlaps)
                ]));

            actualCount = testCase.LayoutReport.RoutingViolationCount;

            testCase.verifyEqual(actualCount, expectedCount);
        end

        function outerLaneEnvelopeCountMatchesTable(testCase)
            expectedCount = uint32(height( ...
                testCase.LayoutReport. ...
                OuterLaneEnvelopeClearanceViolations));

            actualCount = testCase.LayoutReport. ...
                OuterLaneEnvelopeClearanceViolationCount;

            testCase.verifyEqual(actualCount, expectedCount);
        end

        function outerLaneEnvelopeClearanceIsSatisfied(testCase)
            expectedCount = uint32(0);

            actualCount = testCase.LayoutReport. ...
                OuterLaneEnvelopeClearanceViolationCount;

            testCase.verifyEqual(actualCount, expectedCount, ...
                testCase.LayoutReport.RoutingDiagnostic);
            testCase.verifyEqual( ...
                testCase.LayoutReport.Rules. ...
                MinimumOuterLaneEnvelopeClearancePixels, 40);
        end

        function excessiveOuterLanesAreAbsent(testCase)
            testCase.verifyEqual( ...
                testCase.LayoutReport. ...
                ExcessiveOuterLaneClearanceViolationCount, uint32(0), ...
                testCase.LayoutReport.RoutingDiagnostic);
            testCase.verifyEqual( ...
                testCase.LayoutReport.Rules. ...
                MaximumOuterLaneEnvelopeClearancePixels, 180);
        end

        function subviewerCanvasBalanceIsSatisfied(testCase)
            inventory = testCase.LayoutReport.ScopeCanvasInventory;

            testCase.verifyEqual( ...
                testCase.LayoutReport.ScopeCanvasBalanceViolationCount, ...
                uint32(0), testCase.LayoutReport.RoutingDiagnostic);
            testCase.verifyGreaterThanOrEqual( ...
                inventory.StateBBoxUtilization, ...
                testCase.LayoutReport.Rules. ...
                MinimumScopeStateBBoxUtilization);
            testCase.verifyLessThanOrEqual( ...
                [inventory.LeftExpansion; inventory.RightExpansion; ...
                inventory.TopExpansion; inventory.BottomExpansion], ...
                testCase.LayoutReport.Rules. ...
                MaximumScopeCanvasExpansionPixels);
        end

        function bidirectionalOuterDetoursAreAbsent(testCase)
            testCase.verifyEqual( ...
                testCase.LayoutReport. ...
                BidirectionalOuterDetourViolationCount, uint32(0), ...
                testCase.LayoutReport.RoutingDiagnostic);
            testCase.verifyEqual( ...
                testCase.LayoutReport.Rules. ...
                MaximumBidirectionalEnvelopeExcursionPixels, 120);
            testCase.verifyEqual( ...
                testCase.LayoutReport.Rules. ...
                MaximumBidirectionalDetourRatio, 2.20);
        end

        function additionalApproximateCountsMatchTables(testCase)
            expectedCounts = uint32([
                height(testCase.LayoutReport.LabelPathOverlaps)
                height(testCase.LayoutReport. ...
                PathPathCrossingOrPartialOverlaps)
                ]).';

            actualCounts = [
                testCase.LayoutReport.LabelPathOverlapCount
                testCase.LayoutReport. ...
                PathPathCrossingOrPartialOverlapCount
                ].';

            testCase.verifyEqual(actualCounts, expectedCounts);
        end

        function conservativePathWarningsMatchReviewedPairs(testCase)
            warnings = testCase.LayoutReport. ...
                ApproximateRoutingViolations;
            pairs = warnings.ObjectA + " | " + warnings.ObjectB;

            testCase.verifyEqual( ...
                testCase.LayoutReport.LabelPathOverlapCount, uint32(0));
            testCase.verifyEqual( ...
                testCase.LayoutReport. ...
                PathPathCrossingOrPartialOverlapCount, uint32(2));
            testCase.verifyEqual( ...
                testCase.LayoutReport.ApproximateRoutingViolationCount, ...
                uint32(2));
            testCase.verifyTrue(all( ...
                warnings.Category == ...
                "PathPathCrossingOrPartialOverlap"));
            testCase.verifyTrue(any(contains(pairs, "T60 ") & ...
                contains(pairs, "T54 ")));
            testCase.verifyTrue(any(contains(pairs, "T60 ") & ...
                contains(pairs, "T61 ")));
        end

        function routingApiLimitationsAreReported(testCase)
            expectedMinimumCount = 3;

            actualLimitations = ...
                testCase.LayoutReport.RoutingLimitations;

            testCase.verifyGreaterThanOrEqual( ...
                numel(actualLimitations), expectedMinimumCount);
            testCase.verifyTrue(all(strlength(actualLimitations) > 0));
        end
    end
end
