classdef SupervisorInterfacesTest < matlab.unittest.TestCase
    %SUPERVISORINTERFACESTEST Unit tests for AMR supervisor interfaces.

    methods (TestClassSetup)
        function addSourceFolder(testCase)
            projectRoot = fileparts(fileparts( ...
                fileparts(mfilename("fullpath"))));
            sourceFolder = fullfile(projectRoot, "src");
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture(sourceFolder));
        end
    end

    methods (Test)
        function enumCodesAreStable(testCase)
            testCase.verifyEqual( ...
                enumCodes("amr.supervision.LifecycleMode"), ...
                int32((0:5).'));
            testCase.verifyEqual( ...
                enumCodes("amr.supervision.MissionMode"), ...
                int32((0:9).'));
            testCase.verifyEqual( ...
                enumCodes("amr.supervision.NavigationMode"), ...
                int32((0:5).'));
            testCase.verifyEqual( ...
                enumCodes("amr.supervision.SafetyMode"), ...
                int32((0:2).'));
            testCase.verifyEqual( ...
                enumCodes("amr.supervision.EnergyMode"), ...
                int32((0:4).'));
            testCase.verifyEqual( ...
                enumCodes("amr.supervision.HealthMode"), ...
                int32((0:2).'));
            testCase.verifyEqual( ...
                enumCodes("amr.supervision.FaultReason"), ...
                int32((0:10).'));
            testCase.verifyEqual( ...
                enumCodes("amr.supervision.RecoveryAction"), ...
                int32((0:6).'));
        end

        function enumDefaultsAreSafe(testCase)
            testCase.verifyEqual( ...
                amr.supervision.LifecycleMode.getDefaultValue(), ...
                amr.supervision.LifecycleMode.PowerOff);
            testCase.verifyEqual( ...
                amr.supervision.MissionMode.getDefaultValue(), ...
                amr.supervision.MissionMode.Idle);
            testCase.verifyEqual( ...
                amr.supervision.NavigationMode.getDefaultValue(), ...
                amr.supervision.NavigationMode.NavIdle);
            testCase.verifyEqual( ...
                amr.supervision.SafetyMode.getDefaultValue(), ...
                amr.supervision.SafetyMode.Clear);
            testCase.verifyEqual( ...
                amr.supervision.EnergyMode.getDefaultValue(), ...
                amr.supervision.EnergyMode.Normal);
            testCase.verifyEqual( ...
                amr.supervision.HealthMode.getDefaultValue(), ...
                amr.supervision.HealthMode.Healthy);
            testCase.verifyEqual( ...
                amr.supervision.FaultReason.getDefaultValue(), ...
                amr.supervision.FaultReason.None);
            testCase.verifyEqual( ...
                amr.supervision.RecoveryAction.getDefaultValue(), ...
                amr.supervision.RecoveryAction.None);
        end

        function defaultConfigIsDeterministic(testCase)
            config = amr.supervision.createSupervisorConfig();

            testCase.verifyEqual(config.schemaVersion, uint16(1));
            testCase.verifyEqual( ...
                config.supervisorSampleTime, 0.10, AbsTol=1e-12);
            testCase.verifyEqual( ...
                config.timeouts.plannerResponseSeconds, ...
                2.0, AbsTol=1e-12);
            testCase.verifyEqual( ...
                config.recovery.maximumRetries, uint8(3));
            testCase.verifyEqual( ...
                config.energy.criticalSoc, 0.12, AbsTol=1e-12);
            testCase.verifyEqual( ...
                config.energy.lowSoc, 0.25, AbsTol=1e-12);
            testCase.verifyEqual( ...
                config.energy.resumeSoc, 0.80, AbsTol=1e-12);
            testCase.verifyEqual( ...
                config.telemetry.stopResponseLimitSeconds, ...
                config.supervisorSampleTime, AbsTol=1e-12);
            testCase.verifyEqual( ...
                config.defaults.lifecycleMode, ...
                amr.supervision.LifecycleMode.PowerOff);
        end

        function configNameValueOverridesAreApplied(testCase)
            config = amr.supervision.createSupervisorConfig( ...
                SupervisorSampleTime=0.05, ...
                PlannerResponseTimeout=0.75, ...
                MaximumRecoveryRetries=5, ...
                CriticalSoc=0.10, ...
                LowSoc=0.30, ...
                ResumeSoc=0.90, ...
                MinimumDwellTime=0.15, ...
                StopResponseLimit=0.05);

            testCase.verifyEqual( ...
                config.supervisorSampleTime, 0.05, AbsTol=1e-12);
            testCase.verifyEqual( ...
                config.timeouts.plannerResponseSeconds, ...
                0.75, AbsTol=1e-12);
            testCase.verifyEqual( ...
                config.recovery.maximumRetries, uint8(5));
            testCase.verifyEqual( ...
                config.energy.lowSoc, 0.30, AbsTol=1e-12);
            testCase.verifyEqual( ...
                config.telemetry.minimumDwellSeconds, ...
                0.15, AbsTol=1e-12);
            testCase.verifyEqual( ...
                config.telemetry.stopResponseLimitSeconds, ...
                0.05, AbsTol=1e-12);
        end

        function invalidEnergyOrderingIsRejected(testCase)
            testCase.verifyError( ...
                @() amr.supervision.createSupervisorConfig( ...
                CriticalSoc=0.40, LowSoc=0.30), ...
                "AMR:Supervision:InvalidEnergyThresholds");
        end

        function subSampleDwellThresholdIsRejected(testCase)
            testCase.verifyError( ...
                @() amr.supervision.createSupervisorConfig( ...
                SupervisorSampleTime=0.10, MinimumDwellTime=0.05), ...
                "AMR:Supervision:InvalidMinimumDwellTime");
        end

        function oversizedRetryCountIsRejected(testCase)
            testCase.verifyError( ...
                @() amr.supervision.createSupervisorConfig( ...
                MaximumRecoveryRetries=256), ...
                "AMR:Supervision:InvalidRecoveryRetryCount");
        end

        function steadyTelemetryHasExpectedDwell(testCase)
            timeSeconds = (0:0.1:1.0).';
            telemetry = makeTelemetry(timeSeconds);

            metrics = amr.supervision.evaluateSupervisorTelemetry(telemetry);

            testCase.verifyEqual(metrics.sampleCount, uint32(11));
            testCase.verifyEqual( ...
                metrics.durationSeconds, 1.0, AbsTol=1e-12);
            testCase.verifyEqual( ...
                metrics.lifecycle.transitionCount, uint32(0));
            testCase.verifyEqual( ...
                metrics.lifecycle.stateCodes, int32(0));
            testCase.verifyEqual( ...
                metrics.lifecycle.stateDwellSeconds, ...
                1.0, AbsTol=1e-12);
            testCase.verifyTrue(metrics.overallPass);
        end

        function transitionsAndDwellAreMeasured(testCase)
            timeSeconds = (0:1:6).';
            telemetry = makeTelemetry(timeSeconds);
            telemetry.lifecycleMode = int32([1; 1; 2; 2; 2; 4; 4]);
            telemetry.motionPermit = ...
                logical([0; 0; 1; 1; 1; 0; 0]);

            metrics = amr.supervision.evaluateSupervisorTelemetry(telemetry);

            testCase.verifyEqual( ...
                metrics.lifecycle.transitionCount, uint32(2));
            testCase.verifyEqual( ...
                metrics.lifecycle.transitionTimesSeconds, [2; 5]);
            testCase.verifyEqual( ...
                metrics.lifecycle.stateCodes, int32([1; 2; 4]));
            testCase.verifyEqual( ...
                metrics.lifecycle.stateDwellSeconds, ...
                [2; 3; 1], AbsTol=1e-12);
            testCase.verifyEqual( ...
                metrics.stopResponse.requestCount, uint32(1));
            testCase.verifyTrue(metrics.overallPass);
        end

        function shortReturnEpisodeIsReportedAsChattering(testCase)
            timeSeconds = (0:0.1:0.5).';
            telemetry = makeTelemetry(timeSeconds);
            telemetry.navigationMode = int32([1; 1; 2; 1; 1; 1]);

            metrics = amr.supervision.evaluateSupervisorTelemetry(telemetry);

            testCase.verifyEqual( ...
                metrics.navigation.chatteringCount, uint32(1));
            testCase.verifyEqual( ...
                metrics.totalChatteringCount, uint32(1));
            testCase.verifyFalse(metrics.overallPass);
        end

        function oneTickStopResponsePasses(testCase)
            timeSeconds = (0:0.1:0.5).';
            telemetry = makeOperationalTelemetry(timeSeconds);
            telemetry.safetyMode = int32([0; 0; 2; 2; 0; 0]);
            telemetry.motionPermit = ...
                logical([1; 1; 1; 0; 0; 1]);

            metrics = amr.supervision.evaluateSupervisorTelemetry(telemetry);

            testCase.verifyEqual( ...
                metrics.stopResponse.requestCount, uint32(1));
            testCase.verifyEqual( ...
                metrics.stopResponse.maximumResponseTimeSeconds, ...
                0.1, AbsTol=1e-12);
            testCase.verifyEqual( ...
                metrics.stopResponse.missedDeadlineCount, uint32(0));
            testCase.verifyTrue(metrics.overallPass);
        end

        function lateStopResponseFails(testCase)
            timeSeconds = (0:0.1:0.5).';
            telemetry = makeOperationalTelemetry(timeSeconds);
            telemetry.safetyMode = int32([0; 0; 2; 2; 2; 0]);
            telemetry.motionPermit = ...
                logical([1; 1; 1; 1; 0; 1]);

            metrics = amr.supervision.evaluateSupervisorTelemetry(telemetry);

            testCase.verifyEqual( ...
                metrics.stopResponse.maximumResponseTimeSeconds, ...
                0.2, AbsTol=1e-12);
            testCase.verifyEqual( ...
                metrics.stopResponse.missedDeadlineCount, uint32(1));
            testCase.verifyFalse(metrics.overallPass);
        end

        function missingTelemetryFieldIsRejected(testCase)
            telemetry = makeTelemetry((0:0.1:0.2).');
            telemetry = rmfield(telemetry, "healthMode");

            testCase.verifyError( ...
                @() amr.supervision.evaluateSupervisorTelemetry(telemetry), ...
                "AMR:Supervision:MissingTelemetryField");
        end

        function nonIncreasingTimeIsRejected(testCase)
            telemetry = makeTelemetry([0; 0.1; 0.1]);

            testCase.verifyError( ...
                @() amr.supervision.evaluateSupervisorTelemetry(telemetry), ...
                "AMR:Supervision:NonIncreasingTime");
        end

        function mismatchedModeLengthIsRejected(testCase)
            telemetry = makeTelemetry((0:0.1:0.3).');
            telemetry.missionMode = int32([0; 0; 0]);

            testCase.verifyError( ...
                @() amr.supervision.evaluateSupervisorTelemetry(telemetry), ...
                "AMR:Supervision:TelemetryLengthMismatch");
        end

        function numericMotionPermitIsRejected(testCase)
            telemetry = makeTelemetry((0:0.1:0.3).');
            telemetry.motionPermit = zeros(4, 1);

            testCase.verifyError( ...
                @() amr.supervision.evaluateSupervisorTelemetry(telemetry), ...
                "AMR:Supervision:InvalidMotionPermit");
        end
    end
end

function codes = enumCodes(className)
codes = int32(enumeration(className));
end

function telemetry = makeTelemetry(timeSeconds)
sampleCount = numel(timeSeconds);
defaultCodes = zeros(sampleCount, 1, "int32");
telemetry.timeSeconds = timeSeconds;
telemetry.lifecycleMode = defaultCodes;
telemetry.missionMode = defaultCodes;
telemetry.navigationMode = defaultCodes;
telemetry.safetyMode = defaultCodes;
telemetry.energyMode = defaultCodes;
telemetry.healthMode = defaultCodes;
telemetry.faultReason = defaultCodes;
telemetry.recoveryAction = defaultCodes;
telemetry.motionPermit = false(sampleCount, 1);
end

function telemetry = makeOperationalTelemetry(timeSeconds)
telemetry = makeTelemetry(timeSeconds);
sampleCount = numel(timeSeconds);
operationalCode = int32(amr.supervision.LifecycleMode.Operational);
telemetry.lifecycleMode = repmat(operationalCode, sampleCount, 1);
telemetry.motionPermit = true(sampleCount, 1);
end
