function verify_supervisor_requirements()
%VERIFY_SUPERVISOR_REQUIREMENTS Verify the limited requirements YAML contract.
%
% This verification intentionally checks only the repository's constrained
% requirements format. It is not a general-purpose YAML parser.

projectRoot = fileparts(fileparts(fileparts(mfilename("fullpath"))));
requirementsFile = fullfile(projectRoot, "requirements", ...
    "amr_mission_supervisor_requirements.yaml");
assert(isfile(requirementsFile), "AMR:RequirementsFileMissing", ...
    "Requirements file does not exist: %s", requirementsFile);

requirementsText = fileread(requirementsFile);
assert(~isempty(requirementsText), "AMR:RequirementsFileEmpty", ...
    "Requirements file is empty: %s", requirementsFile);
if requirementsText(1) == char(65279)
    requirementsText(1) = [];
end
assert(~any(requirementsText == char(65533)), ...
    "AMR:RequirementsUtf8Decode", ...
    "Requirements text contains a Unicode replacement character.");
requirementsText = strrep(requirementsText, sprintf('\r\n'), newline);
requirementsText = strrep(requirementsText, sprintf('\r'), newline);

assertPatternCount(requirementsText, ...
    '(?m)^schema_version: "1\.0"[ \t]*$', 1, ...
    "AMR:RequirementsSchemaHeader", ...
    "Expected exactly one schema_version header with value ""1.0"".");
assertPatternCount(requirementsText, ...
    '(?m)^package: AMRMissionSupervisor[ \t]*$', 1, ...
    "AMR:RequirementsPackageHeader", ...
    "Expected exactly one AMRMissionSupervisor package header.");
assertPatternCount(requirementsText, ...
    '(?m)^requirements:[ \t]*$', 1, ...
    "AMR:RequirementsListHeader", ...
    "Expected exactly one requirements list header.");

itemPattern = '(?m)^  - id:[ \t]*(REQ_AMR_\d{3})[ \t]*$';
itemStarts = regexp(requirementsText, itemPattern, "start");
itemTokens = regexp(requirementsText, itemPattern, "tokens");
itemIds = string(cellfun(@(token) token{1}, itemTokens, ...
    UniformOutput=false));
expectedIds = compose("REQ_AMR_%03d", 1:37);

assert(numel(itemIds) == numel(expectedIds), ...
    "AMR:RequirementsItemCount", ...
    "Expected %d requirements but found %d.", ...
    numel(expectedIds), numel(itemIds));
assert(numel(unique(itemIds)) == numel(itemIds), ...
    "AMR:RequirementsDuplicateId", ...
    "Requirement IDs must be unique.");
assert(isequal(itemIds(:), expectedIds(:)), ...
    "AMR:RequirementsIdSequence", ...
    "Requirement IDs must be sequential from REQ_AMR_001 to REQ_AMR_037.");

requiredKeys = [ ...
    "id", "summary", "description", "rationale", "asil", ...
    "status", "priority", "keywords", "derived_from"];
derivedReferenceCount = 0;

for itemIndex = 1:numel(itemIds)
    blockStart = itemStarts(itemIndex);
    if itemIndex < numel(itemIds)
        blockEnd = itemStarts(itemIndex + 1) - 1;
    else
        blockEnd = numel(requirementsText);
    end
    itemBlock = requirementsText(blockStart:blockEnd);
    itemId = itemIds(itemIndex);

    for keyIndex = 1:numel(requiredKeys)
        key = requiredKeys(keyIndex);
        if key == "id"
            keyPattern = '(?m)^  - id:[ \t]*';
        else
            keyPattern = "(?m)^    " + key + ":[ \t]*";
        end
        keyCount = numel(regexp(itemBlock, keyPattern, "match"));
        assert(keyCount == 1, "AMR:RequirementsKeyCount", ...
            "%s must contain key '%s' exactly once; found %d.", ...
            itemId, key, keyCount);
    end

    statusToken = regexp(itemBlock, ...
        '(?m)^    status:[ \t]*(Draft)[ \t]*$', "tokens", "once");
    assert(~isempty(statusToken), "AMR:RequirementsStatus", ...
        "%s must have status Draft.", itemId);

    keywordToken = regexp(itemBlock, ...
        '(?m)^    keywords:[ \t]*\[([^\]\r\n]*)\][ \t]*$', ...
        "tokens", "once");
    assert(~isempty(keywordToken), "AMR:RequirementsKeywords", ...
        "%s must use the supported inline keywords list.", itemId);
    keywordValues = strtrim(split(string(keywordToken{1}), ","));
    assert(any(keywordValues == "draft"), ...
        "AMR:RequirementsDraftKeyword", ...
        "%s keywords must contain draft.", itemId);

    asilToken = regexp(itemBlock, ...
        '(?m)^    asil:[ \t]*(Unset|QM|A|B|C|D)[ \t]*$', ...
        "tokens", "once");
    assert(~isempty(asilToken), "AMR:RequirementsAsil", ...
        "%s has an unsupported asil value.", itemId);

    priorityToken = regexp(itemBlock, ...
        '(?m)^    priority:[ \t]*(Unset|Low|Medium|High|Critical)[ \t]*$', ...
        "tokens", "once");
    assert(~isempty(priorityToken), "AMR:RequirementsPriority", ...
        "%s has an unsupported priority value.", itemId);

    summaryToken = regexp(itemBlock, ...
        '(?m)^    summary:[ \t]*"([^"\r\n]*)"[ \t]*$', ...
        "tokens", "once");
    assert(~isempty(summaryToken), "AMR:RequirementsSummary", ...
        "%s must have a quoted, single-line summary.", itemId);
    assert(~isempty(regexpi(summaryToken{1}, '\<shall\>', "once")), ...
        "AMR:RequirementsEarsSummary", ...
        "%s summary must contain the EARS keyword 'shall'.", itemId);

    derivedToken = regexp(itemBlock, ...
        '(?m)^    derived_from:[ \t]*(null|REQ_AMR_\d{3})[ \t]*$', ...
        "tokens", "once");
    assert(~isempty(derivedToken), "AMR:RequirementsDerivedFrom", ...
        "%s derived_from must be null or a requirement ID.", itemId);
    derivedId = string(derivedToken{1});
    if derivedId ~= "null"
        assert(any(itemIds == derivedId), ...
            "AMR:RequirementsDerivedReference", ...
            "%s derived_from references unknown ID %s.", itemId, derivedId);
        derivedReferenceCount = derivedReferenceCount + 1;
    end
end

fprintf([ ...
    'Supervisor requirements limited-format verification PASS | ' ...
    'schema 1.0 | package AMRMissionSupervisor | ' ...
    'requirements %d | derived references %d\n'], ...
    numel(itemIds), derivedReferenceCount);
end

function assertPatternCount(text, pattern, expectedCount, errorId, message)
actualCount = numel(regexp(text, pattern, "match"));
assert(actualCount == expectedCount, errorId, ...
    "%s Found %d.", message, actualCount);
end
