function verify_dwa()
%VERIFY_DWA Verify dynamic-window limits and collision-free local progress.

projectRoot = fileparts(fileparts(fileparts(mfilename("fullpath"))));
addpath(fullfile(projectRoot, "src"));

floorMap = struct( ...
    "bounds", [0, 6, 0, 5], ...
    "walls", [0, 0, 6, 0.10; 0, 4.90, 6, 0.10; ...
        0, 0, 0.10, 5; 5.90, 0, 0.10, 5], ...
    "obstacles", [2.65, 1.80, 0.60, 1.40]);
planningGrid = amr.mapping.rasterizeFloorMap(floorMap, 10, 0.40, false);
safetyGrid = amr.mapping.rasterizeFloorMap(floorMap, 10, 0.30, false);
path = amr.planning.smoothGridPath(planningGrid, ...
    amr.planning.planAStarGrid(planningGrid, [1, 2.5], [5, 2.5]));

config = amr.planning.createDwaConfig();
window = amr.planning.computeDynamicWindow([0.30, 0.20], config);
assert(window(1) >= config.minimumLinearVelocity && ...
    window(2) <= config.maximumLinearVelocity, ...
    "AMR:DwaLinearWindow", "Linear dynamic window exceeds limits.");
assert(window(3) >= -config.maximumAngularVelocity && ...
    window(4) <= config.maximumAngularVelocity, ...
    "AMR:DwaAngularWindow", "Angular dynamic window exceeds limits.");

pose = [1, 2.5, 0];
command = [0, 0];
initialGoalDistance = norm(pose(1:2) - path(end, :));
validCount = 0;
for stepIndex = 1:80
    [command, diagnostics] = amr.planning.selectDwaCommand( ...
        pose, command, path, safetyGrid, config);
    assert(diagnostics.valid, "AMR:DwaNoCandidate", ...
        "DWA found no valid candidate at step %d.", stepIndex);
    validCount = validCount + diagnostics.validCandidateCount;
    nextPose = amr.modeling.integrateDifferentialDrive( ...
        pose, command, config.controlSampleTime);
    assert(amr.mapping.isSegmentCollisionFree( ...
        safetyGrid, pose(1:2), nextPose(1:2)), ...
        "AMR:DwaCollision", "DWA selected a colliding command.");
    pose = nextPose;
end

assert(norm(pose(1:2) - path(end, :)) < initialGoalDistance - 0.50, ...
    "AMR:DwaNoProgress", "DWA did not make sufficient goal progress.");
fprintf("DWA verification passed with %d valid candidate evaluations.\n", ...
    validCount);
end
