function verify_local_costmap()
%VERIFY_LOCAL_COSTMAP Verify novel lidar obstacle marking and inflation.

projectRoot = fileparts(fileparts(fileparts(mfilename("fullpath"))));
addpath(fullfile(projectRoot, "src"));

floorMap = struct("bounds", [0, 8, 0, 6], ...
    "walls", [0, 0, 8, 0.10; 0, 5.90, 8, 0.10; ...
    0, 0, 0.10, 6; 7.90, 0, 0.10, 6], ...
    "obstacles", zeros(0, 4), ...
    "dynamicObstacle", [3.0, 2.7, 0.50, 0.60]);
staticSensorMap = amr.mapping.rasterizeFloorMap(floorMap, 20, 0, false);
dynamicSensorMap = amr.mapping.rasterizeFloorMap(floorMap, 20, 0, true);
staticSafetyMap = amr.mapping.rasterizeFloorMap(floorMap, 20, 0.30, false);
config = amr.sensors.createLidarConfig();
pose = [2.0, 3.0, 0];
scan = amr.sensors.simulateLidar2D(dynamicSensorMap, pose, config);
localMap = amr.planning.buildLocalCostmapFromLidar( ...
    staticSafetyMap, staticSensorMap, scan, pose(1:2), [5, 5], 0.30);

assert(~amr.mapping.isWorldPointOccupied(localMap, pose(1:2)), ...
    "AMR:LocalCostmapRobotOccupied", "Robot cell became occupied.");
assert(amr.mapping.isWorldPointOccupied(localMap, [3.0, 3.0]), ...
    "AMR:LocalCostmapMissingObstacle", ...
    "Novel lidar obstacle was not marked and inflated.");
assert(localMap.bounds(1) >= staticSafetyMap.bounds(1) && ...
    localMap.bounds(2) <= staticSafetyMap.bounds(2), ...
    "AMR:LocalCostmapBounds", "Local bounds exceed global-map bounds.");

fprintf("LiDAR local-costmap verification passed.\n");
end
